### ISSUE TITLE
Delayed jobs running before specified time

### ISSUE THREAD

**Issue by paulcaru** [HangfireIO/Hangfire#1017]
I set up a delayed job to run at 2017-10-05T07:43:45.0000000Z as you can see from the screenshot.
However this was triggered before the specified date time and was run at 2017-10-05T07:43:08.5644829Z. Any idea why?

![image](https://user-images.githubusercontent.com/32538990/31220309-523a3a68-a9c0-11e7-8678-ca492b9428ae.png)

Hangfire.Core -> 1.6.17
Storage -> MySqlStorage 1.0.5

**Comment by pieceofsummer** [comment]
You must have system clock not synchronized between client and Hangfire server. 

Setup NTP time synchronization for all your servers to prevent such issues.

**Comment by paulcaru** [comment]
I checked and the system clock is synchronized. The above case does not always happen always as sometimes it is run after with a 5-10 seconds delay. Any more ideas?

**Comment by pieceofsummer** [comment]
Running somewhat later after scheduled time is actually normal because scheduled jobs are polled every 15 seconds by default (controlled by `SchedulePollingInterval` option):
https://github.com/HangfireIO/Hangfire/blob/129707d66fde24dc6379fb9d6b15fa0b8ca48605/src/Hangfire.Core/BackgroundJobServerOptions.cs#L38
https://github.com/HangfireIO/Hangfire/blob/fecf74a1ff5dd90bb356980b0b7966863ea6a2a8/src/Hangfire.Core/Server/DelayedJobScheduler.cs#L70

But running before scheduled time can be only caused by system time mismatch.

**Comment by paulcaru** [comment]
Hi,

So I did what you suggested on both my application server and database server and now it looks like this.

App
![image](https://user-images.githubusercontent.com/32538990/31381696-92d3ef80-adb5-11e7-8ab6-6ca14baf3d7a.png)

DB

![image](https://user-images.githubusercontent.com/32538990/31381706-9ec0e564-adb5-11e7-87b9-5485c794728f.png)

The problem remains as sometimes it is still running before scheduled time :(

**Comment by pieceofsummer** [comment]
Do you have a client (i.e. the one that enqueues jobs) and Hangfire server (the one that processes them) running on the same server (App), or do they run on different machines?

**Comment by paulcaru** [comment]
Same server. Only DB is different server

**Comment by paulcaru** [comment]
Looks like the issue is somehow related to MySqlStorage because I switched to SqlServerStorage and didnt have issues like the above

**Comment by pieceofsummer** [comment]
Oh, that might explain things! 

MySqlStorage uses `float` data type for `Score` column, but unlike SqlServer's 64-bit float, float in MySql is only 32-bit, so it might be losing precision for large numbers (timestamps).

**Comment by Bogatinovski** [comment]
I also had this issue and for the storage we are using MySql database. On my dev machine the jobs were enqueued about 90 seconds later and on my colleagues' dev machine about 90 seconds earlier. Changing the `Set.Score` column type to a `double` indeed fixed the problem. Now the jobs are enqueued with a delay of maximum 15 seconds which is normal due to the default pooling interval.
