### ISSUE TITLE
Asp Net Core non stop service

### ISSUE THREAD

**Issue by AustinFelipe** [HangfireIO/Hangfire#1022]
Guys, how's doing?

I'm trying to make my Hangfire application always run, but I'm using Asp.Net Core and this link won't work.
http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html

What should I do? 

I appreciate any help.
Thanks.

**Comment by pieceofsummer** [comment]
That depends on how you're running your app.

If you run it as a stand-alone application (i.e. Kestrel serves request directly), you don't need any extra configuration. The drawback is that you'll need to handle all the app lifecycle management by yourself, and Kestrel itself is not that feature-rich.

If you're running behind IIS, then you may try setting the app pool as AlwaysRunning and idle time to 0.
But AspNetCoreModule still seems to not support the automatic start of .net core application on app pool startup (there's an open issue on GitHub, and I have no idea if it was fixed in the latest releases).

You may also run your application on Linux behind nginx. Systemd would handle all your app lifecycle (run on server startup, restart after crashes) for you, and nginx would be a perfect front-end.

As a bonus, you'll be able to:
- serve static files a lot faster (directly by nginx, without going all the way to StaticFiles middleware);
- support http2 multiplexing for static files;
- communicate with Kestrel via Unix socket, which is faster than TCP socket;
- restart/reconfigure frontend independently from the backend;
- and much more I can't remember at the moment :)

But it is only if your app is not using some Windows-only features.

**Comment by carlowahlstedt** [comment]
[Support for .Net Core auto start in IIS](https://github.com/aspnet/IISIntegration/issues/507)

**Comment by DennisDyallo** [comment]
Just a +1 waiting for this to work with IIS :)

**Comment by FreeWillaert** [comment]
I'm trying to understand if this is still an issue.
We're running Hangfire on .Net Core 2.0 with Kestrel behind IIS 10.

After setting the app pool as AlwaysRunning and idle time to 0, it seems the app remains up and the recurring Hangfire tasks keep being scheduled - after a week or so.
We did NOT implement any of the other changes described on http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html

Should we expect issues, or could someone confirm that this is resolved by now?

**Comment by AustinFelipe** [comment]
Well, using AlwaysRunning set to 0 seems to work. I'm going to close this issue.

**Comment by carlowahlstedt** [comment]
@AustinFelipe this does not fix the issue. I tested a site that gets used regularly during the week, but not weekends. AlwaysRunning was already set, but 0 wasn't I changed that and that did not fix the issue. Coming back this morning, the jobs that should have ran this weekend did not. They did, as usual, run once that site was live again.

If you see my comment above, [.Net Core does not currently support keeping an IIS site running](https://github.com/aspnet/IISIntegration/issues/507), but it is in the works.

**Comment by ganniaiuei** [comment]
Microsoft recently published instructions on how to properly configure Always Running apps on IIS using asp.net core.
[docs here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#application-initialization)

**Comment by odinserj** [comment]
Application Initialization module didn’t want to restart an application after deployments when I tested this some years ago due to its implementation details I don’t remember. The only method working for ASP.NET apps is service auto start providers.

For ASP.NET Core apps things were simple, and there was a closed issue with proper configuration in this repo, please search by IdleTimeout.
