### ISSUE TITLE
Excessive connection usage cause timeout exception

### ISSUE THREAD

**Issue by MuratGundes** [HangfireIO/Hangfire#1031]
Hi,

We are using Hangfire in production for recursive web service call every 5 minutes and fireandforget queue for one-time job but we are facing a connection leak and eating up all the connections available in it's application pool and starts hitting a timeout error trying to get a new connection. When we analyze Performance Monitor logs, we saw an unusual situation, there was a lot of active connections. (See screenshot below)
![capture](https://user-images.githubusercontent.com/3201922/31940608-6cfa3aa4-b8c7-11e7-9adc-14021d1aa76a.JPG)

**Code**

```
private void ConfigureAndStartJob(IWindsorContainer container, string hangfirePortalUrl, string hangfireDbConnection)
        {
            HangfireConfigurator.CustomConfiguration.UseSqlServerStorage(hangfireDbConnection);
            HangfireConfigurator.CustomConfiguration.UseActivator(new WindsorJobActivator(container.Kernel));

            JobMonitoringWebApp = WebApp.Start<OwinWebAppStarter>(hangfirePortalUrl);

            BankJobInitializer = container.Resolve<IBankJobInitializer>();

            BankJobInitializer.Init();
            var options = new BackgroundJobServerOptions
            {
                WorkerCount = Environment.ProcessorCount * Convert.ToInt32(ConfigurationManager.AppSettings["HangfireWorkerCount"]),
                ServerTimeout = TimeSpan.MaxValue,
                ShutdownTimeout = TimeSpan.MaxValue,
                ServerCheckInterval = TimeSpan.FromMinutes(1),

                Queues = new[] { "recurring", "fireandforget" }
            };

            GlobalConfiguration.Configuration.UseFilter(new QueueAttribute("fireandforget"));
            GlobalConfiguration.Configuration.UseFilter(new AutomaticRetryAttribute()
            {
                Attempts = 1,
                OnAttemptsExceeded = AttemptsExceededAction.Delete
            });

            BankJobInitializer.ServerStart(options);
        }
```

> *HangfireWorkerCount = 5

> *We have 2 queue.

**Connection String**
**We seperate Hangfire Database in production.**
`<add key="HangfireDbConnection" value="Data Source=<Server_Name>;Initial Catalog=<Db_Name>;Persist Security Info=True;Pooling=true; Max Pool Size=9999;Integrated Security=SSPI;Connection Timeout=10000" />`
`<add name="Db" connectionString="Data Source=<Server_Name>;Initial Catalog=<Db_Name>;Persist Security Info=True;Integrated Security=SSPI;Connection Timeout=600" providerName="System.Data.SqlClient"/>`

**Version**
We were using 1.6.7 until yesterday but we updated to latest release 1.6.17.

**Other Details**
 - Application is implemented with .NET 4.5.2
 - Running on Windows Server 2012R2

Thanks for helping.

**Comment by pieceofsummer** [comment]
Not sure if that is a reason, but I can see two problems with your configuration:

> ShutdownTimeout = TimeSpan.MaxValue,

That would basically deadlock IIS worker shutdown in case some of the jobs refuse to stop normally.

> ServerTimeout = TimeSpan.MaxValue,

This prevents incorrectly stopped servers from being removed from the server list.

**Comment by MuratGundes** [comment]
Hi,
We have a WCF service which is hosted by a Windows Service, not on IIS.

**Comment by MuratGundes** [comment]
We are sure about to background jobs didn't leaking database connections. Our code block is as follows.

```
                using (IUnitOfWork uow = this.unitOfWorkFactory.Create(isolationLevel: isolationLevel))
                {
                    if (!useWithoutTransaction)
                    {
                        uow.Begin();
                    }
                    invocation.Proceed();

                    if (!useWithoutTransaction)
                    {
                        uow.Commit();
                    }
                }
```

We will make a full memory dump and send it to support.

**Comment by odinserj** [comment]
@MuratGundes, I don't see any connection leakage from the dump file you've sent to me. It contains information about 39 physical connections (instances of the `SqlInternalConnectionTds`), where 23 of them are related to dedicated `YOURAPP_HF` database, and 16 of them related to the `YOURAPP` database. The total number of `SqlConnection` class instances is 42 for `YOURAPP` database and 122 for `YOURAPP_HF` database, that is expected when worker count is 40.

Your SQL connection pools configured to have max 9999 connections, and you have 3 pools in total (1 for Hangfire, and 2 for your application, due to different connection strings), so the maximum number of connections should be 9999*3 = 29997, and not the reported value 2.147.483.654 by performance counters. Looks like something is wrong with the counter itself.

> starts hitting a timeout error trying to get a new connection

This issue can also be caused by other factors like the connection count limits enforced by SQL Server instance itself (especially in cloud environments), or worker pool starvation caused by `sp_getapplock` or `wait for`. In the [recent versions](https://www.hangfire.io/blog/releases.html) I greatly reduced the number of required connections by reusing them in distributed locks, and also improved SQL Server's worker thread usage by limiting the time waiting on distributed lock acquisition.

Try to upgrade to the latest versions, and let me know if the problem persist after upgrading.
