### ISSUE TITLE
Query processor could not produce a query plan because of the hints defined in this query. Resubmit the query without specifying any hints and without using SET FORCEPLAN

### ISSUE THREAD

**Issue by ravenet** [HangfireIO/Hangfire#1088]
Hi,

Seem Hangfire version 1.6.17 is killing whole application as below error.

ERROR 2018-01-10 05:50:34,175 105805ms Worker                 LogException       - Error occurred during execution of 'Worker #316fdd97' process. Execution will be retried (attempt #8) in 00:00:51 seconds.
System.Data.SqlClient.SqlException (0x80131904): Query processor could not produce a query plan because of the hints defined in this query. Resubmit the query without specifying any hints and without using SET FORCEPLAN.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   at Dapper.SqlMapper.<QueryImpl>d__125`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:afd9f08b-6364-49f1-9e18-6e7979c8ef7d
Error Number:8622,State:1,Class:16

Can you please help us to fix this annoying error.

Thank you

**Comment by castroal** [comment]
I have the same issue using` Microsoft SQL Server 2012 - 11.0.5058.0 (X64) ` when I try to add a recurring job (`Hangfire.RecurringJob.AddOrUpdate()`)

**Comment by iSatishYadav** [comment]
Is your issue resolved? Have you created all the indexes necessary for Hangfire SQL Storage?

**Comment by AlexeyBogdan95** [comment]
@castroal did you manage to fix the issue?

**Comment by castroal** [comment]
After updating to the latest version of Hangfire it seemed that the problem was solved but, after a while, I had the same error.

After a little bit of investigation I found that the error occurs if there are a lot (millions) of records in the '[Hangfire].[State]' table. Deleting all the records solved the issue for me.

**Comment by AlexeyBogdan95** [comment]
@castroal Am I right that you're using Hangfire.SqlServer `1.6.23`?

**Comment by odinserj** [comment]
Please tell me exact error messages you see to understand what query produce the error. [Originally](https://github.com/HangfireIO/Hangfire/issues/1088#issue-287242980) it was related to the fetching query, and is likely caused by missing indexes or different collations. But since deleting all the `State` entries helped you, the problem is likely to be caused by another query.

**Comment by AlexeyBogdan95** [comment]
@odinserj The issue is reproduced in SQL Server 2012. As for SQL Server 2012, it works fine.
Exception is
`ERROR Hangfire.Server.Worker - Error occurred during execution of 'Worker #0bd485e7' process. Execution will be retried (attempt #178) in 00:05:00 seconds.
System.Data.SqlClient.SqlException (0x80131904): Query processor could not produce a query plan because of the hints defined in this query. Resubmit the query without specifying any hints and without using SET FORCEPLAN.
  at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
  at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
  at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
  at System.Data.SqlClient.SqlDataReader.get_MetaData()
  at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
  at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
  at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
  at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
  at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
  at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
  at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
  at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
  at Dapper.SqlMapper.<QueryImpl>d__125`1.MoveNext()
  at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
  at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
  at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
  at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
  at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
ClientConnectionId:f9e974ba-5c1e-4510-9714-92638597c43b
Error Number:8622,State:1,Class:16
2019-02-27 05:01:32,438 [Worker #8e66cdbf] ERROR Hangfire.Server.Worker - Error occurred during execution of 'Worker #8e66cdbf' process. Execution will be retried (attempt #178) in 00:05:00 seconds.`

**Comment by odinserj** [comment]
This error may be caused by the following things, please tell me which one of the following conditions is `true` for your case.

* `IX_HangFire_JobQueue_QueueAndFetchedAt` that should be used for a seek operation is absent.
* Disabled `row locks` for an index, ensure all of the indexes on the `JobQueue` allow row locks to be taken (index details).
* Collation of the column differs from the `DATABASE_DEFAULT` value.

**Comment by castroal** [comment]
@AlexeyBogdan95 I am using Hangfire.SqlServer.1.6.21
@odinserj Yes the problem might be in another query, but why are you using query hints? Just let SqlServer decide on its own.

**Comment by odinserj** [comment]
@castroal, if you have any of [these problems](https://github.com/HangfireIO/Hangfire/issues/1088#issuecomment-474224431), SQL Server will be unable to produce the correct query anyway. If row locks disabled, then our fetch transaction will block around 200 jobs instead of one, and if you have long-running jobs, then your processing will be stalled from time to time. If you don't have the corresponding index or using different collation, then INDEX SEEK operation will not be performed, and SQL Server will scan entire table on each dequeue that's very bad if you are using multiple queues.

And the worst thing is that in this case those errors will be silently ignored by SQL Server, and it's very hard to consider what's going on.

**Comment by AlexeyBogdan95** [comment]
@odinserj I fixed the issue. 
My steps:
1) drop all the `HangFire` tables in DB
2) update to `1.6.23`

When I ran the app again, the tables were created and I didn't see the error

**Comment by pictoric** [comment]
I'm getting this same error on 1.7.6 on SQL Server 2016 all of a sudden.

**Comment by nponna** [comment]
I see the same error while using 1.7.11.

**Comment by NageshKorimi** [comment]
After re-installing the script the error got fixed

**Comment by berdem** [comment]
For the ones drop in here and still stuck with the error, another thing to check is Compatibility level of you database.
Increase your compatibility level of db at least 100 (SQL Server2008).
If your database compatibility level is lets say 80 (SQL Server 2000) you will see this issue. Increasing it to 100 (ensure everything works ok with 100 ) will solve the problem.

ALTER DATABASE [DBNAME]
SET COMPATIBILITY_LEVEL = 100

**Comment by jonathancounihan** [comment]
Hi,
We are getting the same error (see below for full exception) while accessing our hangfire dashboard, hosted on Azure. We are using version 1.7.19, with our DB schema at 7.

We make use of MSMQ for queue and not SQL server, so I'm not sure what difference the `IX_HangFire_JobQueue_QueueAndFetchedAt` index will make, but I have checked and the index is there. I have also confirmed that the DB collation and the column collation are both `SQL_Latin1_General_CP1_CI_AS`.

> System.Data.SqlClient.SqlException: Query processor could not produce a query plan because of the hints defined in this query. Resubmit the query without specifying any hints and without using SET FORCEPLAN.
> Generated: Wed, 09 Jun 2021 16:08:33 GMT
> 
> System.Data.SqlClient.SqlException (0x80131904): Query processor could not produce a query plan because of the hints defined in this query. Resubmit the query without specifying any hints and without using SET FORCEPLAN.
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
>    at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
>    at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command)
>    at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.<>c__DisplayClass24_0.<GetStatistics>b__0(DbConnection connection)
>    at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
>    at Hangfire.SqlServer.SqlServerMonitoringApi.GetStatistics()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at Hangfire.Dashboard.Pages.HomePage.Execute()
>    at Hangfire.Dashboard.RazorPage.TransformText(String body)
>    at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
>    at Hangfire.Dashboard.MiddlewareExtensions.<>c__DisplayClass1_1.<UseHangfireDashboard>b__1(IDictionary`2 env)
>    at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
>    at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
> ClientConnectionId:94323443-ab68-43a3-a5b4-daa90b92238e
> Error Number:8622,State:1,Class:16
> ClientConnectionId before routing:a31af4c0-243b-4afc-b1a5-419377c625cd
> Routing Destination:b413d1ac8003.tr4118.westeurope1-a.worker.database.windows.net,11006

**Comment by jonathancounihan** [comment]
Found that the issue was this set of queries:

> set transaction isolation level read committed;
select count(Id) from [Hangfire].Job with (nolock, forceseek) where StateName = N'Enqueued';
select count(Id) from [Hangfire].Job with (nolock, forceseek) where StateName = N'Failed';
select count(Id) from [Hangfire].Job with (nolock, forceseek) where StateName = N'Processing';
select count(Id) from [Hangfire].Job with (nolock, forceseek) where StateName = N'Scheduled';
select count(Id) from [Hangfire].Server with (nolock);
select sum(s.[Value]) from (
    select sum([Value]) as [Value] from [Hangfire].Counter with (nolock, forceseek) where [Key] = N'stats:succeeded'
    union all
    select [Value] from [Hangfire].AggregatedCounter with (nolock, forceseek) where [Key] = N'stats:succeeded'
) as s;
select sum(s.[Value]) from (
    select sum([Value]) as [Value] from [Hangfire].Counter with (nolock, forceseek) where [Key] = N'stats:deleted'
    union all
    select [Value] from [Hangfire].AggregatedCounter with (nolock, forceseek) where [Key] = N'stats:deleted'
) as s;
select count(*) from [Hangfire].[Set] with (nolock, forceseek) where [Key] = N'recurring-jobs';

We were missing an index `IX_HangFire_Job_StateName` on the job table, I'm not sure how it got deleted.

**Comment by thomashdk** [comment]
Just got this error in Umbraco 8.16. I'm on the lastest Hangfire 1.7.27.

Is there a easy fix for this?

**Comment by odinserj** [comment]
Unfortunately there's no easy fix for this - some index is missing, and I'm afraid you need to understand which is missing by reconstructing database on local machine by using [this migration](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/DefaultInstall.sql), for example, depending on your schema version, and compare indexes for each table.

**Comment by thomashdk** [comment]
> Unfortunately there's no easy fix for this - some index is missing, and I'm afraid you need to understand which is missing by reconstructing database on local machine by using [this migration](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/DefaultInstall.sql), for example, depending on your schema version, and compare indexes for each table.

Can I drop the tables ?

**Comment by odinserj** [comment]
Yes, you will lose all the data associated with Hangfire, but it will be possible to run the migration script in this case and it will restore all the tables automatically.

**Comment by thomashdk** [comment]
> Yes, you will lose all the data associated with Hangfire, but it will be possible to run the migration script in this case and it will restore all the tables automatically.

How to I run the migration script?

**Comment by Edulopez** [comment]
So, the solution for this is dropping the table?

That's a weird solution, specially for closing this issue.

So basically once we get M+ records we should clean the tables?

**Comment by MuhammadFarooqAwan** [comment]
I had got a same type of exception when I was trying to run Hangfire. Please visit [StackOverflow Site](https://stackoverflow.com/questions/34764637/query-processor-could-not-produce-a-query-plan-because-of-the-hints-defined-in-t) where I have mentioned the solution.

**Comment by Hu8MA** [comment]
now I used 
Hangfire Version="1.8.6"
Hangfire.Core Version="1.8.6"
Hangfire.Dashboard.Basic.Authentication Version="5.0.0" 

but I have problem , when I need to access to dashboard it have error , is tell me 

{"StatusCode":500,"Message":"Query processor could not produce a query plan because of the hints defined in this query. Resubmit the query without specifying any hints and without using SET FORCEPLAN."}  

so what is the correct solve for this problem !!

**Comment by simeyla** [comment]
Definitely recommend [switching the schema name ](https://github.com/HangfireIO/Hangfire/issues/432#issuecomment-386936268) or renaming the tables instead of dropping them. Make sure nobody is accessing the old one by mistake if you change the schema name.

I chose to switch the schema name for minimum downtime and in case I may want to look back at previous jobs.
