### ISSUE TITLE
Why use `Expression` instead of just `Func<T>` or `Action`

### ISSUE THREAD

**Issue by John0King** [HangfireIO/Hangfire#1102]
Why `RecurringJob` and `BackgroundJob`  use `Expression` in `AddOrUpdate` method?

**Comment by burningice2866** [comment]
Because the signature of the method to be fun needs to be serialized and stored in a database so it can later be deserialized again when the time has come for it to actually run.

Technically you could do it with a Func<> directly with a lot of reflection but Expressions is there for exact such purpose so it would be silly not to use it.
