### ISSUE TITLE
JobDisplayNameAttribute not replacing variables in format string

### ISSUE THREAD

**Issue by rfrancisco** [HangfireIO/Hangfire#1136]
The new `JobDisplayNameAttribute` is going to be very useful but right now, atleast for me, It's not working (in a Asp.Net Core project).
```
[JobDisplayName("Job: {0} -> {1}")]
public static async Task Run(string job, string url, TimeSpan timeout)
```
Renders `Job: {0} -> {1}` and
```
[JobDisplayName("Job: {0}")]
public static async Task Run(string job, string url, TimeSpan timeout)
```
Renders `Job: System.Object[]`

I also tested having the method receive a single string argument with no luck.

**Comment by pieceofsummer** [comment]
Yes, this is a known bug, will be fixed in next beta :)

**Comment by zerokewl88** [comment]
This does not work in ASP.NET 4.6 - is this supported ?

I have 2 Hangfire Projects that share the same SQL Storage. Jobs from the 'FrontEnd' come in and JobTitles are ok because of the assemblies, but the 'Backend' do not - and this i have read and realise is due to missing references. 

So i thought i could use this JobDisplayName, or DisplayName attribute, but i still see the 'Could not find target assembly message' and not seeing the Job Titles changed.

Is this possible ? 

Thank you.
