### ISSUE TITLE
Can you support timed task processing for seconds level units?

### ISSUE THREAD

**Issue by ghd258** [HangfireIO/Hangfire#1262]
Is it possible to support seconds of time task processing, or does Hangfire support minutes or more of time task processing?

**Comment by acraven** [comment]
I've had a _very_ quick look; it looks like the cron expression as a string handled by RecurringJobManager does not support seconds. See CronExpression.Parse(cronExpression)

It would seem possible if the cron parsing handled seconds, but perhaps there is a reason this isn't supported.

I'm tempted to dig into this a bit more and pass a CronExpression object to RecurringJobManager.AddOrUpdate rather than a string and cascade accordingly.

**Comment by burningice2866** [comment]
Its not so much a matter of the Manager not supporting seconds, than Cron Expressions by nature doesn't support seconds.

https://en.wikipedia.org/wiki/Cron#CRON_expression

**Comment by ghd258** [comment]
That's not supported, can't it be supported in a different way, there are a lot of tasks that need to be done in seconds, so you can't use Hangfire, Quartz. NET can support it, I believe Hangfire can do it, or learn how Quartz does it

**Comment by burningice2866** [comment]
You can look at the [IBackgroundProcess](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/IBackgroundProcess.cs) interface. IMO its a better way to run tasks that needs to run that frequently since it allow you to fully control how often to run.

Version 1.7 will support expressions that includes seconds by using [Cronos](https://github.com/HangfireIO/Cronos) instead of NCrontab

**Comment by vindberg** [comment]
How can we use the Cronos seconds expression for the RecurringJob.AddOrUpdate function? Is is already supported?

**Comment by pieceofsummer** [comment]
@vindberg even with seconds in cron expression, it still won't give you a second resolution for your jobs because the throttler for recurring jobs still would trigger on a minute basis.

**Comment by vindberg** [comment]
Ok, thanks for the feedback. Am using hostedservice in core now.

**Comment by odinserj** [comment]
Support for seconds implemented in the latest betas of 1.7.0 so you can just pass six-part cron expression and it will work. However, you'll need to tweak the `BackgroundJobServerOptions.SchedulePollingInteval` option correspondingly to avoid extra delays, because default polling interval is 15 seconds.
