### ISSUE TITLE
Where should I  start/Add RecurringJob when work with asp.net-core  ?

### ISSUE THREAD

**Issue by John0King** [HangfireIO/Hangfire#1281]
Here's  a list that I think I can put `RecurringJob.AddOrUpdate` .
- `Startup.Configure`  . probably will run before `IApplicationLifetime.ApplicationStarted ` ; 
-  registe a action for `IApplicationLifetime.ApplicationStarted ` ,this is how Hangfire.AspNetCore start the BackgroundJob.
- use `IHostedService`  and regist to DI
- some reflect for specified class/interfaece/atrribute when Hangfire's BackgroundJob start (not sure current support or not)

**Comment by pieceofsummer** [comment]
`Startup.Configure` is a perfect place to do that. You can inject a `IRecurringJobManager` service instance there, and there's no need to wait for IApplicationLifetime.ApplicationStarted to register your jobs.

**Comment by John0King** [comment]
Will you consider 
> use `IHostedService` and regist to DI

**Comment by odinserj** [comment]
Yes, you can also use an `IHostedService` to add recurring jobs or any other place. The thing is that to add a recurring job, there will be a call to the storage. And if you don't want to prevent your application from starting if there are issues with your storage (this will be a case with using `Startup` class), you'd like to have some kind of retries. And for these cases, `IHostedService` is a better solution.

Regarding attributes, I don't think this should be implemented in Hangfire itself, because it heavily depends on an application itself, and generic solution will be too bad.

**Comment by John0King** [comment]
@odinserj  I see your point.
