### ISSUE TITLE
Start Processing a job in enqueue after deleting all processing jobs

### ISSUE THREAD

**Issue by AHassanabadi** [HangfireIO/Hangfire#1314]
I configured the server as below code:
```
var options = new BackgroundJobServerOptions
{ 
    WorkerCount = 1
}; 
GlobalConfiguration.Configuration.UseSqlServerStorage("ExJobConnection", new SqlServerStorageOptions()
{
    SchemaName = "Push"
}).UseConsole();
GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 5 });
app.UseHangfireDashboard("", new DashboardOptions());
app.UseHangfireServer(options);
```
I set `WorkerCount`  to 1 to process one job at the moment, this is works fine if there is no exception in Jobs logic.

my problem is: as below screenshot shows one of jobs take a long time to be executed but some time I want to delete it manually and expect the next one be proceeded immediately , there is no something to process one of en-queued jobs manually.

Is it about config or my expect is not reasonable ?

![processing](https://user-images.githubusercontent.com/6092619/50141035-af052280-02bb-11e9-8b8d-f229abe9b836.png)

Thanks in Advance.

**Comment by odinserj** [comment]
When the *Delete* button is triggered, dashboard will find the corresponding background job and move it to the *Deleted* state. Background job execution itself will not be stopped, unless you are using `IJobCancellationToken` and check it in your background job as [written here](http://docs.hangfire.io/en/latest/background-methods/using-cancellation-tokens.html). 

This is by design, because the only method of stopping unknown user code is to use the `Thread.Abort` method that's very dangerous to use by default, without knowing anything about your code as it can lead to cases (including deadlocks), where the only option is to kill the whole application.

**Comment by odinserj** [comment]
Duplicates #1298

**Comment by AHassanabadi** [comment]
Thank you.
So, Deleting a job does not means stop and kill it ? so what is the purpose of `Delete` button just moving it to Delete state while that job still is working ?
If I understand like so, that to be start next job I should kill it by `IJobCancellationToken`  or `Abort` it.

**Comment by odinserj** [comment]
Yes, the method itself should detect that the job was deleted by someone, and throw the `JobAbortedException` in this case. The `IJobCancellationToken.ThrowIfCancellationRequested` method performs that check, and throws the required exception for you. If your job is based on a large loop, you can call `ThrowIf...` method every N iterations.
