### ISSUE TITLE
Could not load type Microsoft.Extensions.Logging.Internal.FormattedLogValues

### ISSUE THREAD

**Issue by blahblehblah** [HangfireIO/Hangfire#1344]
After upgrading to aspNet Core 3.0 i am facing this issue on startup/run > 

Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Source: Hangfire.AspNetCore

**Comment by odinserj** [comment]
Thanks for reporting this, it's caused by calling the [`CreateStateObject`](https://github.com/HangfireIO/Hangfire/blob/4a5404062e61ce6883df53b3209baddf511f73d7/src/Hangfire.AspNetCore/AspNetCore/AspNetCoreLog.cs#L50) method that's completely unneeded and can be safely removed with `messageFunc()` as this works fine on both ASP.NET Core 2.1 and 3.0. The fix will be available in 1.6.23, but you can workaround it by configuring any other logging as shown below.

```csharp
services.AddHangfire((provider, config) => config
    .UseLogProvider(new ColouredConsoleLogProvider())
    .UseSqlServerStorage("Database=WebApplication33; Integrated Security=SSPI;"));
```
