### ISSUE TITLE
Threading / TaskScheduler

### ISSUE THREAD

**Issue by Cephei** [HangfireIO/Hangfire#1361]
> Hangfire uses its own fixed worker thread pool to consume queued jobs.

As far as I can tell, the above statement is somewhat misleading. `Worker` processes will be a fixed amount using `TaskCreationOptions.LongRunning`. However, asynchronous background jobs will use the `ThreadPool` for processing while the dedicated, Worker thread `Wait()` for completion.

These fixed tasks are used by a JobPerformer to execute - which behind the scenes invokes the job function. If your function returns a `Task`, the core processor will **not** `await` it, but actually calls `Task.Wait()`. This is synchronous.

My observations are that:
1. Wait() will completely block on the dedicated non-ThreadPool thread initially created.
2. Any asynchronous code within your job e.g. `async / await` calls will likely resume on an actual ThreadPool thread. You can prove this to be true by simply calling an `await Task.Delay` in your function.

Therefore, `TaskCreationOptions.LongRunning` does nothing but create a wasted thread in async use cases. What I believe this project really needs to consider is actually providing dedicated ThreadPools or more likely, a TaskScheduler to its `Worker`. That way async jobs can more efficiently make use of threads. I would consider looking at Akka.net's Helios. https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs

e.g. Background jobs that use Dataflow blocks for processing. These linked-blocks can process many jobs in parallel using specified TaskSchedulers.

**Comment by odinserj** [comment]
@Cephei sorry for confusion, that information was written when async/await usage was rare enough. 

Actually, [BackgroundTaskScheduler](https://github.com/HangfireIO/Hangfire/blob/dev/src/Hangfire.Core/Processing/BackgroundTaskScheduler.cs) has already been landed to the `dev` branch, so it will be available in the upcoming 1.7.0 release. However it will not be enabled by default until 2.0 to not to double the number of threads in an application – storage APIs are still synchronous, and therefore workers can't use asynchronous dispatchers yet.

But to avoid the confusion and since async APIs are quite common today, I've decided to implement a transitional way of handling async methods via `SynchronizationContext`. While this may sound weird, because it looks like they've been completely replaced by `TaskScheduler`, it's the only option to properly handle async work items and not to cause deadlocks for those who're still using `Parallel.For(Each)` methods and not to overflow the `TaskScheduler.Id` property.
