### ISSUE TITLE
Is there a way to delete named queues?

### ISSUE THREAD

**Issue by s-tokutake** [HangfireIO/Hangfire#1364]
I use many named queues, and want to delete unused queues becase the dashborad's enqueued list (' /hangfire/jobs/enqueued ') is too long.
I use the pro edition and storage is redis, and I guess named queues is saved as a set which key is ` hangfire:queues `.
Can I remove a named queue safety using SREM command directly ?
Or Does hangfire provide any methods to do that?

**Comment by odinserj** [comment]
Since you can have continuations and other logic that should be performed on background job completion (like completing a batch), you can't just drop those jobs. Try putting the `LatencyTimeoutAttribute` on your job methods to not to call their methods when some timeout is exceeded. In this case all the required completion work will be done, and your methods will not be fired.

**Comment by ItsKaleb** [comment]
I also have a similar issue where I am using queues tied to instances of a program to run tasks against each of the instances. I am able to delete jobs so they don't continue queuing against dead queues, but I have not found a way to actually delete the queue itself, as they continue to clutter up the dashboard page.

Aside from manually deleting entries in the JobQueue table, is there a way to clean the queues up when they are no longer assigned to a server?
