### ISSUE TITLE
Blocked Threads (possible stupid question)

### ISSUE THREAD

**Issue by gregpakes** [HangfireIO/Hangfire#1384]
This might be a stupid question...

Whenever we take a dump of our processes, it always shows 8+ threads blocked/waiting.  These threads are always blocked/waiting in Hangfire code.  I'm just wondering if this is normal or if there is something wrong.  Here is a common stacktrace:

```
1. System.Threading.ThreadHelper.ThreadStart(System.Objec...)
2. System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Objec...)
3. System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolea...)
4. System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolea...)
5. System.Threading.ThreadHelper.ThreadStart_Context(System.Objec...)
6. ThreadPoolTaskScheduler.LongRunningThreadWork(...)
7. System.Threading.Tasks.Task.ExecuteEntry(Boolea...)
8. System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRe...)
9. System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolea...)
10. System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolea...)
11. System.Threading.Tasks.Task.ExecutionContextCallback(System.Objec...)
12. System.Threading.Tasks.Task.Execute(...)
13. System.Threading.Tasks.Task.InnerInvoke(...)
14. ServerProcessExtensions+<>c__DisplayClass1_0.b__0(...)
15. ServerProcessExtensions.RunProcess(...)
16. Hangfire.Server.ServerProcessExtensions.Execute(Hangfire.Server.IServerProcess, Hangfire.Server.BackgroundProcessContex...)
17. Hangfire.Server.InfiniteLoopProcess.Execute(Hangfire.Server.BackgroundProcessContex...)
18. Hangfire.Server.ServerProcessExtensions.Execute(Hangfire.Server.IServerProcess, Hangfire.Server.BackgroundProcessContex...)
19. Hangfire.Server.AutomaticRetryProcess.Execute(Hangfire.Server.BackgroundProcessContex...)
20. Hangfire.Server.ServerProcessExtensions.Execute(Hangfire.Server.IServerProcess, Hangfire.Server.BackgroundProcessContex...)
21. Hangfire.Server.ServerHeartbeat.Execute(Hangfire.Server.BackgroundProcessContex...)
22. System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolea...)
23. WaitHandle.WaitOneNative(...)
```

Here is some diagnostics from Raygun APM (Top 3 slowest methods):

![image](https://user-images.githubusercontent.com/102243/55372921-1be0b780-554f-11e9-9969-468a81007d4d.png)

I guess my question is whether this is normal?  Our application is certainly not a heavy user of Hangfire and so it surprises me that there always seems to be multiple threads blocked.

**Comment by odinserj** [comment]
Question that can be answered can't be stupid. It's OK for those threads to sleep most of the time, because they do periodic work. Those sleeping threads don't affect your application, because OS knows about their state and don't schedule them to a processor. 

And those methods are running in dedicated threads to be isolated from thread pool's cooperative multitasking, where large backlog (for example, too many web requests) will prevent from executing our logic in time.

**Comment by gregpakes** [comment]
Thank you so much @odinserj.  So you're saying that yes this is normal.

My only further question is that during the times these dumps are taken, hangfire is not doing anything.  We barely use it during the day, so would you say it's normal to have so many threads used?  There are literally no jobs scheduled for 20+ hours, yet there are always these threads blocked.  Is that normal?

**Comment by odinserj** [comment]
It's not absolutely free, because each thread consumes 1MB of memory for its stack. However, threads in waiting state don't consume CPU, because they aren't scheduled to any processor. In Hangfire 2.0 it will be possible to reduce the number of threads, but anyway there will be additional threads sitting idle, because it's the only way to ensure important tasks like heartbeat will be performed even if there's a high pressure by other concurrent work.

If you'd like to learn more about this topic, I'd recommend reading [Concurrent Programming on Windows](https://www.amazon.com/Concurrent-Programming-Windows-Architecture-Development-ebook-dp-B0015DYKI4/dp/B0015DYKI4/ref=mt_kindle?_encoding=UTF8&me=&qid=) book by Joe Duffy as it's a great read.
