### ISSUE TITLE
AwaitJob with OnAnyFinishedState ignores ContinuationSupports attribute

### ISSUE THREAD

**Issue by jschuringa** [HangfireIO/Hangfire#1387]
We create a new `ContinuationsSupportAttribute` and add it to the global filters

`GlobalFilters.Filters.Add(new ContinuationsSupportAttribute(new HashSet<string>{SucceededState.StateName, FailedState.StateName, DeletedState.StateName });`

so that when a job fails, we continue on anyway. However, when using `BatchJobClient.AwaitJob(antedecentId, batch => batch.Enqueue((Interface i) => i.method(), description, BatchContinuationOptions.OnAnyFinishedState);`, it seems that the `ContinuationsSupportAttribute` is getting ignored, and our job is hanging because the batch is still waiting for the failed job to finish. 

Are we using the `ContinuationsSupportAttribute` correctly, or is there another way to get our batches to continue from a failed job?

**Comment by odinserj** [comment]
I'm afraid batch will not be completed if there's at least one failed job, because batches don't consider a background job in the Failed state as completed. I'm planning to either make the Final state to be a final one itself, or create another state for background jobs completed with an exception that will be a final one to cover these cases. 

But meanwhile it's better to place `AutomaticRetry(OnAttemptsExceeded = AttemptsExceededAction.Delete))` attribute on job methods that should be deleted after all attempts are exhausted.
