### ISSUE TITLE
Does Hangfire support Failover machanism ?

### ISSUE THREAD

**Issue by Michaelmilk** [HangfireIO/Hangfire#1401]
Hi guys, I encounter one issue:
There're multiple Hangfire server instances, and each instance will take the job from Sql server, however, if one instance is down unexpectedly when executing job(unexpected network issue or machine's down), does Hangfire will Failover current executing job to other instances? or is there any way to make it happen? 

Anyone have nice way to handle this case?

**Comment by odinserj** [comment]
Hangfire doesn't schedule jobs to workers directly. Instead, workers pick up jobs from a queue. While queue implementations *should* implement the failover correctly, because that's a primary use case Hangfire solves, there *may* be implementations that don't respect this behavior. So I can't say anything regarding all the storages.

For example, Hangfire.SqlServer package has two fetching implementations – using long-running transactions that span the entire lifetime of a job, that block a job from other workers and release it once transaction or connection is failed. Another mode is using timeouts. You can enable it by setting the `SqlServerStorageOptions.SlidingInvisibilityTimeout` (to 5 minutes, for example). When a job is fetched, timestamp is set, and other workers unable to fetch that job before timeout is exceeded. However, there's a timer that extends that timeout periodically, so it works even for long-running jobs.

**Comment by markalanevans** [comment]
I don't think this answers the question.

If redis fills up, how can I have SQL table that creates a backlog of jobs that then get stuck in, and then have a work that is always looking and moving them from primary storage to secondary storage or slowly processing them...
