### ISSUE TITLE
Very high network when deploy ms sql server database on a difference server

### ISSUE THREAD

**Issue by minhhungit** [HangfireIO/Hangfire#1456]
Version: latest 1.7.3
Storage: MS SQL Server (2017)

I have **two servers**: one for website and one for database

![image](https://user-images.githubusercontent.com/2279508/60272929-427c7780-991f-11e9-9109-da1f7ba5b17c.png)

And this is after I change to use MSMQ store on same server with website (**mssql server database is still placed on database server**)

![image](https://user-images.githubusercontent.com/2279508/60273010-6344cd00-991f-11e9-9799-28927b791242.png)

I am not sure if this is an issue, can anyone review this issue pls

**Comment by odinserj** [comment]
Could you tell me more about your workload, throughput and job types you are using?

**Comment by minhhungit** [comment]
hi @odinserj   I just use fire and forget method, very simple but large message 

```csharp
BackgroundJob.Enqueue(() => RequestHandler(request, trackId, null));

[AutomaticRetry(Attempts = 0, OnAttemptsExceeded = AttemptsExceededAction.Fail)]
[Queue(HangfireQueueName.SubmitJob)]
public void RequestHandler(ProcurementAddRq request, long trackId, PerformContext performContext)
{
    // ...
}
```

**Comment by minhhungit** [comment]
And this is what I configured

```csharp
GlobalConfiguration.Configuration
    .UseFilter(new JobContext())
    .UseSqlServerStorage("MyHangfireDatabase", new Hangfire.SqlServer.SqlServerStorageOptions
     {
         CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
         SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
         QueuePollInterval = TimeSpan.Zero, // Set only when using SlidingInvisibilityTimeout
         DisableGlobalLocks = true, // Set only if `Schema 6` migration is applied
         UsePageLocksOnDequeue = true, // Set only if `Schema 6` migration is applied
         UseRecommendedIsolationLevel = true,
         JobExpirationCheckInterval = new TimeSpan(0, 0, 20)
     })
    .UseConsole();


var bjOptions = new BackgroundJobServerOptions
    {
        Queues = queueNames,
        WorkerCount = Environment.ProcessorCount * 25
    };

    app.UseHangfireServer(bjOptions);
```
---
after I got problem with network, I changed to use MSMQ 
```csharp
GlobalConfiguration.Configuration
    .UseFilter(new JobContext())
    .UseSqlServerStorage("MyHangfireDatabase")
    .UseMsmqQueues(@".\Private$\hangfire-{0}", queueNames)
    .UseConsole();
```

**Comment by minhhungit** [comment]
**JobContext** class
```csharp
public class JobContext : IServerFilter
    {
        [ThreadStatic]
        private static string _trackId;

        public static string TrackId
        {
            get
            {
                return _trackId;
            }
            set
            {
                _trackId = value;
            }
        }

        public void OnPerformed(PerformedContext filterContext)
        {
            
        }

        public void OnPerforming(PerformingContext context)
        {
            context.Items.Add("jobFiredDateTimeUtc", DateTime.UtcNow);
        }
    }
```

**Comment by odinserj** [comment]
You also changed to use a local SQL Server instance after getting a network problem, that's why the problem is gone. If the size of the `ProcurementAddRq` message is *large*, then network usage will be *large* too. Could you tell me more about its size?

The best solution for large messages is to store their body outside of Hangfire. In NAS, Azure Blobs, etc. – i.e. in storages that are designed for storing large payloads. And pass in Hangfire only some unique identifier of that payload.

**Comment by minhhungit** [comment]
@odinserj 
>You also changed to use a local SQL Server instance after getting a network problem, that's why the problem is gone

no sir, database is still on database server, only MSMQ queue on same server with website

**Comment by minhhungit** [comment]
>The best solution for large messages is to store their body outside of Hangfire. In NAS, Azure Blobs, etc. – i.e. in storages that are designed for storing large payloads. And pass in Hangfire only some unique identifier of that payload.

anyway, this is good tips, I will notice it, thanks

**Comment by odinserj** [comment]
Hm, that's strange, because MSMQ alone can't cause this, because only integer-based job identifiers are stored there. Anyway I believe the problem is caused by large argument sizes. I'm closing the issue, so if the problem persists after moving large arguments outside of Hangfire, just open a new one.

**Comment by minhhungit** [comment]
@odinserj  But why network is high more and more, you can look at the graph

**Comment by odinserj** [comment]
That's a good question, especially considering that outbound traffic is low when comparing to the inbound one. But we should first ensure it wasn't caused by huge argument sizes. Please run the following query and show me the output:

```sql
SELECT TOP (20) [Id], [InvocationData], DATALENGTH([Arguments]) as [Length] FROM [HangFire].[Job]
ORDER BY [Length] DESC
```

Also, try upgrading the [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/) package to the latest version (or install it if it's not installed explicitly). And please tell me what platform you are using, e.g. .NET Framework or .NET Core and its version.

**Comment by minhhungit** [comment]
@odinserj here is result

![image](https://user-images.githubusercontent.com/2279508/60280219-b3765c00-992c-11e9-98e0-bf7058b7b7c3.png)

and I use .Net Framework :)

**Comment by odinserj** [comment]
So now I don't believe that message sizes are causing high network usage. Does the problem persists when using `QueuePollInterval` equal to `TimeSpan.FromSeconds(1)`?

**Comment by minhhungit** [comment]
@odinserj  Sorry I can not test it right now, it's production. I don't dare to try again

Unlucky I just have only one server for Test
I may try again with QueuePollInterval = TimeSpan.FromSeconds(1) in future

**Comment by minhhungit** [comment]
One more thing I noticed is after I upgraded hangfire from version 1.6 => 1.7.3 (msmq store) then I see that MSMQ look quite slow. maybe problem is because WorkerCount is high for version 1.7.3 (but normal with version v1.6) => not sure if there is an issue like too much competing consumers ???

>WorkerCount = Environment.ProcessorCount * 25

I will update worker lower tomorrow and will let you know

**Comment by odinserj** [comment]
So how many workers do you have in total? How many background jobs are processed per second?

**Comment by minhhungit** [comment]
@odinserj  WorkerCount = 100, about 3 messages every second
It looks I don't need 100 workers right, 10 workers are okay ?

**Comment by minhhungit** [comment]
hi @odinserj I'm back
I tried to adjust hangfire and here is result, hope it will help you understand the problem
Please read comment in screenshot...

---
![image](https://user-images.githubusercontent.com/2279508/60342844-c9435a00-99dc-11e9-8b3c-a56933783a95.png)

---

![image](https://user-images.githubusercontent.com/2279508/60343311-e3ca0300-99dd-11e9-99cc-b3358968b961.png)

---

![image](https://user-images.githubusercontent.com/2279508/60343085-5edee980-99dd-11e9-955d-bd4cf27ecb8a.png)

---

### _And this is better result, after I use msmq store in same server with web server:_


![image](https://user-images.githubusercontent.com/2279508/60343226-b0877400-99dd-11e9-8d74-a9aa434102bd.png)

---

![image](https://user-images.githubusercontent.com/2279508/60343462-399eab00-99de-11e9-9e08-129d06d86f8a.png)

---

Let me know if you have any question

**Comment by minhhungit** [comment]
One more thing, my system use IIS web garden 
and yesterday I see that in rush hours we have about 30 messages per seconds ( ~ request per second )

**Comment by odinserj** [comment]
@minhhungit thanks a lot for the images. Actually I've found a potential issue that may lead to increased network consumption (please see the referenced commit), but still don't understand why it happens and why it's increasing over time. 

I believe the best way to investigate this is to check all the logs generated by Hangfire for that time to see whether there are any exceptions, and use [Wireshark](https://www.wireshark.org/) to analyze what protocol generates the traffic and what queries are involved if it's caused by MSSQL's TDS protocol – it has handy packet inspector and you can obtain queries without any magic involved.

Sub-second polling interval is enabled for some test harness sites running on the cheapest Azure plans (on different machines), and I didn't see any problems with it. The issue is really weird.

I will release the referenced commit with 1.7.4 today.

**Comment by minhhungit** [comment]
Thank you @odinserj I will try version 1.7.4 soon

**Comment by minhhungit** [comment]
For simplicity I created new database on same server with our website, then I don't care about network issue, I have some notes:
- use sql store: still get high latency 
- use msmq: fast and good for me at this time with low latency
- I used latest version 1.7.4

Unlucky I can not test the latest version with database from difference server, maybe later.

I will close this issue, if someone has problem like me then they will create new issue 

Thank you for your help @odinserj
