### ISSUE TITLE
How to implement new hangfire storage

### ISSUE THREAD

**Issue by minhhungit** [HangfireIO/Hangfire#1458]
Hi team @odinserj , as title I want to implement new hangfire storage (for example memory storage). 

I know there is a [Hangfire.MemoryStorage](https://github.com/perrich/Hangfire.MemoryStorage) but they said it is not good for production

![image](https://user-images.githubusercontent.com/2279508/60376148-10f6cf80-9a37-11e9-9454-caa959c1c82d.png)

So, any tips where should I start ? any document for it ?

Thank you

**Comment by djesmond** [comment]
I'm just gonna throw in a idea here
I assume that you don't/can't use any of the currently available storage options.

A simple but maybe not proper solution comes to mind. 
You could consider using [EF Core](https://github.com/aspnet/EntityFrameworkCore) and just use its in memory storage options (instead of connecting to an SQL database). I've used it for testing suites so i don't know its viability in a production environment. But it would be pretty easy to setup and would almost be plug and play with HangFire as it is (since it emulates an SQL database).
EF Core is an ORM so it isn't exactly built for this kind of thing though.

Why do you need an in memory solution by the way?

**Comment by minhhungit** [comment]
@djesmond thank you for you comment.

That is a great idea but I am not sure it can clean up resource in a periodic, I have many messages everyday so I worry that a big table in memory all time will cause problem. is that right ?

**Comment by djesmond** [comment]
@minhhungit I see. So what you need is a storage option with a max size essentially? 
I do not know the implementation details of the Hangfire.MemoryStorage, but could you simply fork that project and modify it for your needs? I think it will be your best bet for getting started atleast. 
I'm assuming that they want to discourage people from using the current version in production due to its current implementation. So you will have to deal with this as well. Maybe some of the devs in the repo can give you hints to what sections of the code are problematic.

**Comment by minhhungit** [comment]
I was hoping we have some document about storage to read before I type something

Anyway, thank you @djesmond for your advise 👍

**Comment by minhhungit** [comment]
@djesmond
FYI, I created a memory extension for SQL Server storage and it should work like SQL + MSMQ but in memory

https://github.com/minhhungit/Hv.Hangfire.SqlServer.Memory

next, I will research "true" in-memory storage, hope I can implement it

**Comment by djesmond** [comment]
@djesmond Thanks! I will keep the link if i need it in the future. Glad you made progress!
