### ISSUE TITLE
Hangfire Recurring Job gives ERROR in next execution

### ISSUE THREAD

**Issue by awais-ilyas** [HangfireIO/Hangfire#1522]
I have a recurring job, it works perfectly first time, but after the next execution, it gives ERROR. However, there isn't any exception or error in my GetPendingTrips() method. Can some guide me what is the issue here in next attempt of a recurring job?

`RecurringJob.AddOrUpdate<ITripManager>(nameof(ITripManager), job => job.GetPendingTrips(), Cron.Minutely);`

**Comment by sgtobin** [comment]
I have the same issue. I have deployed a .net core 2.2 app in a Linux container running under cloud foundry. There are no Failed jobs in the dashboard. I have checked the Cloud Foundry application logs but do not see an error. Its frustrating because I have other jobs that are running fine. All jobs are using the same cron: Cron.Daily(23). Hover over the error and the tooltip says: 'Could not load the job. See inner exception for the details.' If I submit the job through the UI - it works. If I let it run under the scedule - it fails. Hangfire is v 1.7.6 using sql server. 

Here is the recurring job code....
`
RecurringJob.AddOrUpdate("Load workers", () => workersJob.Execute(null), Cron.Daily(23), queue: "batch");
`

**Comment by sgtobin** [comment]
k - just discover something about my setup.
I have two apps that share the same hangfire database.

App A processes queue QA and has the dashboard enabled. 
App A creates J1 and J2 as recurring jobs.
Job J1 and job J2 are processed on queue QA. 
Job J1 is initially ok but "later"shows the ERROR for next execution. J2 is fine all the time.

App B process queue QB and has the dashboard enabled. 
App B does not create any recurring jobs.
App B has access to the code for job J2 only.
The recurring jobs tab on App B dashboard shows job J1 with 'Could not load file or assembly' error.

I think that app B is causing J1 to fail on app A because it does not have access to the code. This may only happen when I bring up the Recurring Job tab on the app B dashboard and it shows the 'Could not load file or assembly' error. 

I dont think app B should cause problems for app A as app B is not being asked to process those jobs. They are just showing on its dashboard. I would be happy to filter those jobs out of Bs dashboard but I dont see a mechanism to do that.

**Comment by Nitin2706** [comment]
Facing the same issue. Any workaround?

**Comment by sgtobin** [comment]
I tried disabling the dashboard on the app that could not 'see' all the code for the recurring jobs to test if simply bringing up the dashboard caused the problem but the problem remains. 

I changed my code so both apps could 'see' all the code for all the jobs even if the app was not running those jobs and the problem went away. 

For now that works for me but in general, if an app is not executing a job, it should not cause it to be un-executable by other apps that are executing the job, simply because they use a shared hangfire sql persistence config.

**Comment by awais-ilyas** [comment]
I have realized that Hangfire will not work continuously on background in IIS server, it will immediately stop the recurring job when there isn't any activity on the server. So in order to run the recurring job you need to do the following steps as mentioned in this article.

https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html

**Comment by sgtobin** [comment]
This has nothing to do with IIS. It has to do with multiple apps sharing the same sql instance when both apps do not have the code for all jobs. In my case, I have 2 .net core apps running inside docker containers on linux boxes under cloud foundry. I dont believe you should close this - at least not for the reason you did.

**Comment by sgtobin** [comment]
I have opened a separate ticket as it appears that while we had the same symptoms, we have different causes.
[New Issue:](https://github.com/HangfireIO/Hangfire/issues/1533)

**Comment by chrisevans9629** [comment]
I followed the documentation for ensuring that aspnetcore is always running in IIS and I'm still getting this error

**Comment by j0nimost** [comment]
I have this error with my worker services.
