### ISSUE TITLE
Performance issues in special conditions

### ISSUE THREAD

**Issue by Svisstack** [HangfireIO/Hangfire#1553]
When I have Hangfire server with more workers than machine cores then UI rendering is very slow like the 20s vs 200ms, also I can't saturate all the CPU.

However when I start Hangfire servers in separate processes it works great, CPU is saturated and UI responding fast.

When I allocate multiple servers in the single process then UI also working so slow that I couldn't even get the response.

I'm trying to figure out why it's happening, there is some documentation on how the workers running jobs to figure what could cause such behavior?

My main questions: How to make sure I can have eg. 256 workers in the single hangfire server without causing hangfire UI performance issues and saturate the CPU? Now it looks like there is some limit which I can't break (~20% CPU) and adding more workers in the single process only worsening performance while starting new workers in servers operated by separate operating processes works correctly.

I'm expecting that adding more workers to hangfire servers will respond the same as adding more workers across hangfire servers in separate operating system processes.

I'm using .NET Core 2.2 and Hangfire 1.7.7, my load is generated via the async Task method which consists of I/O await and CPU processing work. Adding significantly more workers than CPU threads ensuring that all Tasks on the thread pool have the CPU work to do and not wait on the I/O operation to finish.

**Comment by odinserj** [comment]
You can try delegating all the async method invocations to the workers themselves by setting the `BackgroundJobServerOptions.TaskScheduler` property to `null`. Doing this will greatly unload CLR's Task Scheduler that may be blocked, depending on the nature of your background jobs.

```csharp
app.AddHangfireServer(options =>
{
    options.TaskScheduler = null;
});
```

After setting it to `null`, you can go further and set the `ThreadPriority` of each worker thread to `ThreadPriority.BelowNormal` to tell OS scheduler to schedule them only if there are no other work (like related to the UI).

Unfortunately there's no direct way to do this other than by setting it via `Thread.CurrentThread` property in every background job method, so current implementation will be confusing. However it will be possible to do that in 1.7.8 (because of [this commit](https://github.com/HangfireIO/Hangfire/commit/985ad77456f5226abf5859524ddf6990a7c20412)) with a custom server (like [this one](https://github.com/odinserj/ConsoleApp13/blob/master/CustomBackgroundJobServer.cs)).

**Comment by odinserj** [comment]
That method relates to asynchronous background processes that are supported by Hangfire since 1.7.0, but no built-in processes were implemented in this way (because storage APIs are still synchronous). I/O operations will not cause threads to be blocked in this case, so we can keep the number of worker threads low.

**Comment by Svisstack** [comment]
Thanks for the information. If I can suggest something, in my opinion, Hangfire related processes should be by default highest priority as they represent here higher layers to manage tasks - like the UI thread in Windows Applications, it also should never be blocked.

I will try to make changes with the current version and deliver feedback as I will migrate to the 1.7.8 as soon as released.

**Comment by Svisstack** [comment]
Using ```TaskScheduler = null``` I experienced a strange issue where after 30 minutes no work was done (0% CPU)

![image](https://user-images.githubusercontent.com/864295/68149639-8838f480-ff3e-11e9-8a6c-ff9850a079f0.png)

**Comment by Svisstack** [comment]
Final thoughts. Managed to get this working on the ThreadPool, issues were somewhere on my side but experienced a bug using a ```TaskScheduler = null``` where after some time all workers were doing nothing.

Thanks for the information's above.
