### ISSUE TITLE
Unable to manually trigger jobs cross-platform due to TimeZone

### ISSUE THREAD

**Issue by joshlrogers** [HangfireIO/Hangfire#1554]
We recently moved to an Azure Linux web app running the dashboard with our backend servers being windows VM's.  Using guidance from #1268 we were able to get the dashboard to work by registering a ITimeZoneResolver implementation but we are now unable to manually trigger any of our recurring jobs.  When we redeploy the same code to a Windows App Service we are then able to manually trigger those same jobs so there seems to still be an issue with Timezones.

Error Message: Object reference not set to an instance of an object.
Stack Trace:
Hangfire.RecurringJobEntity.GetChangedFields(Nullable`1& nextExecution):161
Hangfire.RecurringJobEntity.IsChanged(IReadOnlyDictionary`2& changedFields, Nullable`1& nextExecution)
Hangfire.RecurringJobManager.Trigger(String recurringJobId):74
Hangfire.Dashboard.BatchCommandDispatcher+<Dispatch>d__2.MoveNext():223
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):46
 
Hangfire.Dashboard.AspNetCoreDashboardMiddleware+<Invoke>d__5.MoveNext():700
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):46

Are we forced to host the dashboard and scheduling servers on the same OS?  Is there a workaround for this? 

Further info: 
If we replace the timezone with UTC when scheduling the jobs we are able to manually trigger them as well.

**Comment by joshlrogers** [comment]
We solved our issue.  We had to change
`services.TryAddSingleton<ITimeZoneResolver>(new TimeZoneConverterResolver());`
to
`serviers.AddSingleton<ITimeZoneResolver>(new TimeZoneConverterResolver());`

No matter where we placed the `TryAdd` in the registration process, before or after the UseHangfire directive, the DefaultTimeZoneResolver() was still being used.  As soon as we switched to `AddSingleton` our breakpoint inside the `TimeZoneConverterResolver` began getting hit and things started working as expected.

**Comment by odinserj** [comment]
Thanks for reporting this and for the solution. That's strange why calling `services.TryAddSingleton` *before* calling the `AddHangfire` method doesn't work, because default implementation also uses the [`TryAddSingleton`](https://github.com/HangfireIO/Hangfire/blob/985ad77456f5226abf5859524ddf6990a7c20412/src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs#L55) method that shouldn't override the previous registration.

But nevertheless, `NullReferenceException` here is a bug that cause background job to be triggered anyway without recording the invocation. That's a minor issue that will be fixed in 1.7.8.
