### ISSUE TITLE
Question about CoreBackgroundJobPerformer

### ISSUE THREAD

**Issue by Psypher9** [HangfireIO/Hangfire#1597]
I was looking around and have a quick question.

[This method here](https://github.com/HangfireIO/Hangfire/blob/82f3f61b874c95a00019dd256a4b0bf7b447b04e/src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs#L213-L218), why is the parameter an `object` and then cast back to a `Tuple<MethodInfo, object, object[]>` when each of the references provides their argument as a  `Tuple<MethodInfo, object, object[]>`? I'm just curious to know.

[Here](https://github.com/HangfireIO/Hangfire/blob/82f3f61b874c95a00019dd256a4b0bf7b447b04e/src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs#L169-L211)
[Also here](https://github.com/HangfireIO/Hangfire/blob/82f3f61b874c95a00019dd256a4b0bf7b447b04e/src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs#L155-L168)
[Then also here](https://github.com/HangfireIO/Hangfire/blob/82f3f61b874c95a00019dd256a4b0bf7b447b04e/src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs#L118-L132)

**Comment by pieceofsummer** [comment]
Because it is also used as a task method here:
https://github.com/HangfireIO/Hangfire/blob/82f3f61b874c95a00019dd256a4b0bf7b447b04e/src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs#L157-L163

`TaskFactory.StartNew<TResult>()` expects a `Func<object, TResult>` as an argument, so there’s really not much one can do about it.

**Comment by Psypher9** [comment]
Ah, that makes sense. I missed that bit. Thanks for clarifying!
