### ISSUE TITLE
Hangfire cannot find assembly after updating assembly

### ISSUE THREAD

**Issue by flipdoubt** [HangfireIO/Hangfire#1736]
When a user schedules a recurring job defined in the JobProject assembly at version 1.0.0.0, everything works fine. In the database, the `Hangfire.Job.InvocationData` column contains type info for `"JobProject.IMyJob, JobProject, Version=1.0.0.0, Culture=neutral, PublicToken=null"`. When I update JobProject to version 2.0.0.0, the scheduled job fails with the following message:
```
System.IO.FileNotFoundException: 
Could not load file or assembly 'JobProject, Culture=neutral, PublicKeyToken=null'. 
The system cannot find the file specified.
```
I assume this is because the version number does not match the version of the scheduled job. If I delete the scheduled job and recreate it, things work fine. But how do we fix this without recreating the jobs?

**Comment by odinserj** [comment]
Try using `IGlobalConfiguration.UseIgnoredAssemblyVersionTypeResolver` extension method to register a special resolver for this case that strips out version information before resolving a type. Call it with other configuration logic for Hangfire when initializing an application:

```csharp
GlobalConfiguration.Configuration
    .UseXXXStorage()
    .UseIgnoredAssemblyVersionTypeResolver();
```

You can also save some bytes when serialising type names, and it also can solve problems with assembly version, since this information isn't saved when using simple assembly names with the following method:

```csharp
GlobalConfiguration.Configuration
    .UseXXXStorage()
    .UseIgnoredAssemblyVersionTypeResolver()
    .UseSimpleAssemblyNameTypeSerializer();
```

**Comment by flipdoubt** [comment]
Thanks, @odinserj. I was not aware of `UseSimpleAssemblyNameTypeSerializer()`, and this gets me most of what I need. Our code already uses a custom type resolver to deal with the fact that we load "plugin" assemblies from different directories. Once I changed our custom type resolver to lookup the implementation in our DI container (Lamar) by simple type and assembly names, Hangfire now runs jobs implemented by updated versions of the same assemblies.

Thanks again!
