### ISSUE TITLE
Hangfire DB blocking

### ISSUE THREAD

**Issue by denizzengin** [HangfireIO/Hangfire#1745]
Hi,

### Hangfire Update query causing db blocking. While looking at blocking query, it seems a update query for JobQueue table.

Query;
`(@queues1 nvarchar(4000),@queues2 nvarchar(4000),@timeout int,@lockResource nvarchar(4000),@pollingDelayMs int,
@pollingQuantumMs int,@result int output) 
set nocount on; 
set xact_abort on; 
set transaction isolation level read committed;  

update top (1) JQ set FetchedAt = GETUTCDATE() output INSERTED.Id, INSERTED.JobId, INSERTED.Queue, INSERTED.FetchedAt 
from [NEMS_SOLUTION].JobQueue JQ with (forceseek, paglock, xlock) 
where Queue in (@queues1,@queues2)
and (FetchedAt is null or FetchedAt < DATEADD(second, @timeout, GETUTCDATE()));`

![hangfire](https://user-images.githubusercontent.com/12685380/95170121-9b8eb880-07bc-11eb-9b96-dce049ad1087.png)

Hangire Options :
**new Hangfire.SqlServer.SqlServerStorageOptions
{
	PrepareSchemaIfNecessary = false,
	SchemaName = "SCHEMA_NAME",
	CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
	SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
	QueuePollInterval = TimeSpan.FromSeconds(1),
	UseRecommendedIsolationLevel = true,
	UsePageLocksOnDequeue = true,
	DisableGlobalLocks = true

});**

What might be causing this?

Note : We have 7 job and only one runs every minute.

**Comment by odinserj** [comment]
Please remove the `UsePageLocksOnDequeue` option. I've also removed it from the recommended ones, because of additional locking between fetch query and Hangfire's transactions, and transactions will block fetch queries. Although that page lock works really well and decreases CPU consumption when there's a huge number of background jobs to be processed, it will block clients when the number of jobs is relatively low. And since the latter scenario is more frequent, I've removed that recommendation.

**Comment by denizzengin** [comment]
Hi again,
I removed but this solution didn't work. Any other solution or reason why is this happen ? (other settings is same with above)

**Comment by odinserj** [comment]
But what are the wait resources now? Try also to set `QueuePollInterval` to `TimeSpan.Zero`, in this case more efficient polling implementation will be used, so multiple workers will not be issuing queries to the database during idle periods. Also ensure you are running the latest version of Hangfire.Core and Hangfire.SqlServer.
