### ISSUE TITLE
Replace OWIN.dll

### ISSUE THREAD

**Issue by Chris-dot-net** [HangfireIO/Hangfire#1757]
Are there any plans to replace owin.dll? Version 1.0.0.0 dll should not be maintained in highly secured infrastructures and therefore hangfire will be blocked in those environments. Also owin.dll is over 12 years old..

**Comment by odinserj** [comment]
It's not referenced in .NET Core (and future .NET 5.0) packages anyway, and .NET Framework becomes obsolete too. But what do you mean by the following words?

> Version 1.0.0.0 dll should not be maintained in highly secured infrastructures and therefore hangfire will be blocked in those environments. Also owin.dll is over 12 years old..

`Owin` package does not contain any code, it only defines only a single interface – `IAppBuilder`, and [nothing else](https://www.fuget.org/packages/Owin/1.0.0/lib/net40/Owin.dll/Owin/IAppBuilder). So it's hard to find anything more secure than this package, perhaps only [`System.Ben`](https://www.fuget.org/packages/System.Ben) package is more safe.

**Comment by Chris-dot-net** [comment]
We have a multi-tenant sharepoint 2013 environment with thousands of users. One of our security restrictions is to prevent using old code. Even though Owin only has a single interface, there ARE solutions where it is replaced, even by Microsoft themselves. Therefore, are there plans to update the package or do I have to find a replacement for hangfire (or update the package myself)?

**Comment by odinserj** [comment]
This is a breaking change and such dependencies can't be changed before Hangfire 2.0 is released. I don't know when this will happen, because have more plans for 1.X version. As I've said before, Hangfire for .NET Core does not have such old dependencies so can be used in all environments.

I honestly don't understand why Owin package released in 2012 is too old, while Sharepoint 2013 isn't. And .NET Framework also becomes obsolete with release of .NET 5.0. I understand you are willing to make everything work in your environment, but making this step will break many other environments, and unfortunately don't see any magical solution that will work for every side 🤷‍♂️.

**Comment by Chris-dot-net** [comment]
That's just what I was looking for. Even a "no" is a valid answer (dunno why most ppl don't see it that way).
Thanks alot. ;)
