### ISSUE TITLE
Hangfire server with 0 Workers still processing jobs

### ISSUE THREAD

**Issue by luisxkimo** [HangfireIO/Hangfire#1785]
We have configured 2 servers both with 20 workers in startup, with MS SQL database configuration for the Hangfire system.

If we change the configuration for one in database to this:
```json
{
  "WorkerCount":0,
  "Queues":["default","recurring"],
  "StartedAt":"xxxx"
}
```

![Screenshot_1](https://user-images.githubusercontent.com/6990299/103086380-c848b400-45e4-11eb-9bff-3a42216a55a5.png)

We see the change in the Hangfire dashboard, **and we expect that the server with 0 workers doesn't receive jobs**, but however, it still processing some of the recurring jobs( we use recurring jobs to test this behavior)

Is this the expect functionality?

EDIT: **same behavior with the `Queues` configuration**

**Comment by Frazi1** [comment]
@luisxkimo
`WorkerCount` setting corresponds to the number of workers that process normal jobs in Hangfire.


https://github.com/HangfireIO/Hangfire/blob/f0d1588da1e9f2a61a3c1d8c833025ebf4f38ffa/src/Hangfire.Core/BackgroundJobServer.cs#L198

A recurring job is a special entity that is processed by `RecurringJobScheduler`.

https://github.com/HangfireIO/Hangfire/blob/f0d1588da1e9f2a61a3c1d8c833025ebf4f38ffa/src/Hangfire.Core/BackgroundJobServer.cs#L200


> Is this the expect functionality?

I think, the answer is yes. This is by design.

In order to meet your requirements, you can implement your own version of `BackgroundJobServer` which will not use a `RecurringJobScheduler`. Unfortunately, you will have to do some copy-paste from Hangfire because that class does not have any extension points.

**Comment by luisxkimo** [comment]
Hi @Frazi1 ,

About that you said I derive that:

1. WorkerCount is stablished **on the startup of BackgroundJobServer**. It means that If I modify the configuration in database, I need to restart the service
2. Recurring jobs are executed by other *entity* different to a normal *worker*. So the basic configuration (WorkerCount and so on) doesn't apply to this kind of jobs

Its right?

Thanks

**Comment by Frazi1** [comment]
Hi @luisxkimo
1.
> WorkerCount is stablished on the startup of BackgroundJobServer. It means that If I modify the configuration in database, I need to restart the service

I believe, that the lines you see in the database are for display only. When `BackgroundJobServer` is started, it will insert some data about itself into the database so that you can later see it on your Dashboard page. Modifying the database manually will not affect the actual number of workers. It will only affect the numbers you can see on the dashboard.

To sum up, you shouldn't change any database records manually. All the configuration needs to be done on the server start up via `BackgroundJobServerOptions` class. You have to restart the server every time you make changes.

2.

> Recurring jobs are executed by other entity different to a normal worker. So the basic configuration (WorkerCount and so on) doesn't apply to this kind of jobs

This is half-way true. The recurring jobs work as following:

1.There is a process called `RecurringJobScheduler` responsible for checking the cron expressions of your jobs. When `RecurringJobScheduler` sees that it is time for a job to be executed, it will create a  **normal**  job and put it into one of Hangfire's queues (by default, `default` queue is used). The job is not executed at this point, it is only `Enqueued`.

Any Hangfire application instance that has a `RecurringJobScheduler` running will be able to monitor the cron expressions and queue up an instance of the recurring job. Such settings as `Queues` or `WorkerCount` do not affect that.

You can define which queue is used by a recurring job. For example, you can put your recurring jobs into `recurring` queue. 
```c#
RecurringJob.AddOrUpdate<MyClass>(c => c.SomeMethod(), Cron.Daily, queue: "recurring");
```

2. After a job is enqueued into some queue, it will be picked up by a normal worker (the one configured by `WorkerCount` setting) that operates on the queue.

You can configure some of your servers to operate on `recurring` queue.
```c#
new BackgroundJobServerOptions() { Queues = new []{"recurring"} }; //This server will take jobs from `recurring` queue only. It will not use any other queues that are not specified here.
```
**Note:**
In certain scenarios, Hangfire can re-queue your job (i.e, for a retry). In that case, the job is requeued to the `default` queue which may not be what you expect. You can address [this great article](https://earwicker.com/Hangfire_A_Tale_of_Several_Queues.html) to get more information about it. The article also provides a solution to make sure your jobs are always re-queued to the correct queue.


I hope, I was able to explain it. Please let me know if you have any other questions.

**Comment by luisxkimo** [comment]
Hi @Frazi1 

Thank you for your explanation. Solved my doubts and lot of useful info extra.

Regards
