### ISSUE TITLE
Changing cron expression of recurring job causes immediate execution - Vers 1.7.18

### ISSUE THREAD

**Issue by Raj4git** [HangfireIO/Hangfire#1797]
A job was scheduled to run only on Monday @4am "0 0 1 11 *" and we changed to run every day 3 am "0  3 * * *". 
This was caused immediate execution of the job when new code deployed dashboard accessed.

As per old ticket https://github.com/HangfireIO/Hangfire/issues/728. Its been fixed under version 1.7.8 but we observed same behaviour in version 1.7.18

**Comment by odinserj** [comment]
Could you tell me how did you change it, via `RecurringJob.AddOrUpdate` method or something else (like deleting it first)? Also please tell at what time you've changed it (approximately), what was its last execution date (approximately) and when it was created (approximately) to reproduce the issue. Please also tell what storage you are using.

**Comment by Raj4git** [comment]
Hello, 
We have used RecurringJob.AddOrUpdate method to change it.
It was set to execute in November 0 0 1 11 * so it never executed before. We change to run that job daily 3 am "0 3 * * *".
We are using postgres SQL for storage.

**Comment by CBlaize** [comment]
Coincidentally, we ran into the same issue earlier today.

On version 1.7.16 using Redis storage.

We had an existing schedule for "0 2 * * 0" (2am Sunday) UTC which was registered using `RecurringJob.AddOrUpdate` some time over 24 hours ago.

Around 12pm CST today ,  we updated the schedule by changing only the timezone from UTC to CST.  This update was performed through `RecurringJob.AddOrUpdate` as well (we did not delete it first).  Unfortunately, I do not have the last execution date.

We weren't able to reproduce the issue so we decided to add code to first delete the job if it already exists, and then call `.AddOrUpdate()` with the hope that the problem we experienced was related to logic involving the last execution date.

**Comment by Raj4git** [comment]
We are not removing the job before we call .AddOrUpdate. Its happened with quite few jobs for us when we changed schedule from November 0 0 1 11 * to "0 3 * * *".

**Comment by Raj4git** [comment]
Hello team, do you have any updates on it?

**Comment by odinserj** [comment]
Thank you for your patience and reporting this. I was able to catch the problem – when changing time zone without changing the cron expression, `LastExecution` or `CreatedAt` value is taken into account when calculating the next execution, instead of current time. @colinblaise, thanks for the hint! So at least one reason was fixed.

But when cron expression is changed, then current time is always being used when calculating the next occurrence. @Raj4git please test the new version once it's available and let me know if the issue persists.

https://github.com/HangfireIO/Hangfire/blob/3b7a44bda08a1e1edf2227f0fa1901f407074f74/src/Hangfire.Core/RecurringJobEntity.cs#L298

**Comment by Raj4git** [comment]
Thanks @odinserj , I will update the ticket with the findings on the new version.
