### ISSUE TITLE
How to remove old servers from hagnfire in Blue/Green deployment?

### ISSUE THREAD

**Issue by Raj4git** [HangfireIO/Hangfire#1894]
We have blue-green stack deployment. We keep inactive stack up and running for 24hrs that results in old servers keep getting used in hangfire job processing. Is there any way we can remove old servers or stop getting added?

or 

I’m mostly interested in any best practices for this sort of set up. does anyone have any practical advice for stopping jobs from running on old code in a blue-green deployment scenario?

**Comment by Frazi1** [comment]
That's a good question.

You can try to use an incremental strategy for naming your queues. For example, if you put everything into `detault` queue, you can do `default-{serverVersion}` instead. So, when upgrading your app, it will start putting new jobs in another queue that is not accessible from older servers.

However, all the jobs that existed at the upgrade time will remain in the older queue and will not be processed by the new server. If that's inappropriate, you can introduce migration logic that will re-queue existing jobs to the new queue at startup.

Unfortunately, I'm not aware of any easier way to do it with Hangfire. If your app only runs Hangfire and does not do anything else, it will be simpler to just terminate older instances completely.

**Comment by Frazi1** [comment]
@Raj4git
Hm, I think I got you wrong the first time.

Actually, there is a way to stop just the Hangfire server without shutting down the whole app.

## Idea
The idea is as following:
```c#
//Make it a controller action, for example
[HttpPost]
public async Task StopHangfire([FromServices] IServiceProvider provider)
{
    TimeSpan gracefulShutdownDelay = TimeSpan.FromSeconds(10);
    var hostedServices = provider.GetService<IEnumerable<IHostedService>>(); //Get all hosted services in container
    foreach (var hostedService in hostedServices)
    {
        if (hostedService is BackgroundJobServerHostedService) //Filter only Hangfire servers
        {
            using var cts = new CancellationTokenSource(gracefulShutdownDelay);
            await hostedService.StopAsync(cts.Token); //Stop it
        }
    }
}
```

## Problem
But it will not work because Hangfire registers its servers as `Transient` instances in the container.
https://github.com/HangfireIO/Hangfire/blob/07627d4261852381fc980906f48d32af2c281f1e/src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs#L131
 And when you call `var hostedServices = provider.GetService<IEnumerable<IHostedService>>();`, it will create new servers instances, not return the existings ones.

## Workaround
To overcome that, you need to register that instance as `Singleton` instead.

1. So, copy-paste this method into your project. Note that you also need to copy other methods that are being used
https://github.com/HangfireIO/Hangfire/blob/07627d4261852381fc980906f48d32af2c281f1e/src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs#L124-L140
2. Rename it something like `AddHangfireSingletonServer`
3. Change the service scope from `Transient` to `Singleton`

Result:
```c#
public static IServiceCollection AddHangfireSingletonServer(
            [NotNull] this IServiceCollection services,
            [NotNull] Action<IServiceProvider, BackgroundJobServerOptions> optionsAction)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));
            if (optionsAction == null) throw new ArgumentNullException(nameof(optionsAction));
            
            //here
            services.AddSingleton<IHostedService, BackgroundJobServerHostedService>(provider =>
            {
                var options = new BackgroundJobServerOptions();
                optionsAction(provider, options);

                return CreateBackgroundJobServerHostedService(provider, options);
            });

            return services;
        }
```
4. Use it in your `Startup.cs`

## Integration
You can hit the exposed `StopHangfire` API from within your CI pipeline to shutdown Hangfire.


@Raj4git please let me know if it helps. Maybe we can create a PR for Hangfire to allow shutting down the servers without copy-pasting so much.

@odinserj thoughts?

**Comment by Raj4git** [comment]
Thank you all for your response. Sorry, couldn't able to reply earlier. 
We got help from the DevOps team to create a release/pipeline to stop the servers. We didn't want to any changes to the code and everyone agreed with that option.

**Comment by krzysiek-b** [comment]
@Frazi1 That was also something I considered but still looking for a more clean solution which will involve less maitenance. 

I noticed @pieceofsummer described a cleaner solution but I do not understand how does `IOptionsMonitor<HangfireServerOptions>` update running server worker count. When I try to follow the WorkerCount property flow is looks like is value copied and there is not reference so it can get updtae automatically when options are changed.

@pieceofsummer  Can you say more on whay have you found?
