### ISSUE TITLE
Netsparker needs update on Hangfire JQuery version.

### ISSUE THREAD

**Issue by thotasp** [HangfireIO/Hangfire#1899]
Netsparker Enterprise identified the target web site is using jQuery and detected that it is out of date.

Since this is an old version of the software, it may be vulnerable to attacks.
jQuery before 3.0.0 is vulnerable to Cross-site Scripting (XSS) attacks when a cross-domain Ajax request is performed without the
dataType option, causing text/javascript responses to be executed.

In jQuery versions greater than or equal to 1.0.3 and before 3.5.0, passing HTML containing <option> elements from untrusted
sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute
untrusted code. This problem is patched in jQuery 3.5.0.

Kindly update JQuery version to use Hangfire on production sites. Or please provide some guidelines to use latest JQuery version.

Thanks so much.

**Comment by odinserj** [comment]
Thanks for reporting this. Actually Hangfire uses 1% of the features and is unlikely vulnerable. However this also means that it's simple to upgrade the dependencies without any changes, because minimum number of features are used, and it's likely there will be no any breaking changes. So I've upgraded jQuery to 3.6.0 for the upcoming Hangfire 1.7.25 to avoid any alarms by Netsparker Enterprise or other vulnerability scanners.

**Comment by thotasp** [comment]
Thanks a lot for upgrading and sharing JQuery usage details! We are looking forward for Hangfire 1.7.25 release!

**Comment by odinserj** [comment]
You are welcome, it's already released, please see https://www.hangfire.io/blog/2021/08/30/hangfire-1.7.25.html

**Comment by thotasp** [comment]
Thanks for letting me know!
