### ISSUE TITLE
The queue name of the job triggered by requeue button in the dashboard is always default

### ISSUE THREAD

**Issue by liuzhenyulive** [HangfireIO/Hangfire#1900]
Hi guys,

I found the queue name of the job tiggered by requeue button in the dashboard is always default.

![image](https://user-images.githubusercontent.com/23184470/125446214-49bf36fd-157e-4551-80a9-32d35df33b0f.png)

![image](https://user-images.githubusercontent.com/23184470/125446355-217cd1f5-02e4-441e-bb9e-866c1428896d.png)

Because after receiving the requeue request, it always uses the default no-argument constructor to create a new EnqueuedState

https://github.com/HangfireIO/Hangfire/blob/88504456704b6fa590a25a694f1e877b922a9da1/src/Hangfire.Core/Dashboard/DashboardRoutes.cs#L122-L125

https://github.com/HangfireIO/Hangfire/blob/88504456704b6fa590a25a694f1e877b922a9da1/src/Hangfire.Core/Dashboard/DashboardRoutes.cs#L192-L196

 https://github.com/HangfireIO/Hangfire/blob/88504456704b6fa590a25a694f1e877b922a9da1/src/Hangfire.Core/States/EnqueuedState.cs#L89-L92

So I had to create an attribute and apply it to each method of jobs to solve this issue?

``` c#
    internal class RequeueJobIssueFixAttribute : JobFilterAttribute, IApplyStateFilter
    {
        public void OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            var status = context.NewState as EnqueuedState;
            if (status == null)
            {
                return;
            }

            if (status.Queue != EnqueuedState.DefaultQueue)
            {
                return;
            }

            var jobDetails = context.Storage.GetMonitoringApi().JobDetails(context.BackgroundJob.Id);
            var queueName = jobDetails.History.FirstOrDefault(d => d.StateName == EnqueuedState.StateName)?.Data["Queue"];
            if (!string.IsNullOrEmpty(queueName))
            {
                status.Queue = queueName;
            }
        }

        public void OnStateUnapplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            return;
        }
    }
```
Hope this helps,  Will you guys fix it at next release? So we needn't to use this attribute in every method.

Thanks

**Comment by liuzhenyulive** [comment]
Hi Frazi1, thanks for your response and the article is helpful, then requeue to default queue is this a bug or is it designed in this way?

**Comment by Frazi1** [comment]
I believe there is a conversation with @odinserj somewhere either in GitHub issues or in https://discuss.hangfire.io/ where he confirmed it to be the expected behavior.

Also, checkout https://github.com/HangfireIO/Hangfire/releases/tag/v1.8.0-beta3 release.
It mentions the following change:
```
Added – Introduce the Job.Queue property, so jobs now can have their own queue specified.
```
With that new feature, Hangfire's behavior may be changed. But I haven't tested it myself.

**Comment by liuzhenyulive** [comment]
got it, thank you.

**Comment by ggleo08** [comment]
I get the same problem now.
[the code here](https://github.com/HangfireIO/Hangfire/blob/c23b01061860b4f5b5692e23e8f8cbdbe4681a8b/src/Hangfire.Core/AutomaticRetryAttribute.cs#L274), create a new **State** instance instead of the original **State** when reschedule job.
Is there any reason to  discard the original State ?
