### ISSUE TITLE
Question: Why did hangfire transfer processing to another node?

### ISSUE THREAD

**Issue by kvvinokurov** [HangfireIO/Hangfire#1969]
I started the task. After some time, for some reason it was passed on to another node of the three. Why could this happen? Hangfire runs on Windows Service. Servers and Hangfire  services were not restarted.

Information from [State] datatable:
Id	JobId	Name	Reason	CreatedAt	Data
776915	367888	Enqueued	NULL	2021-11-11 18:28:46.043	{"EnqueuedAt":"2021-11-11T18:28:45.9484834Z","Queue":"default"}
776916	367888	Processing	NULL	2021-11-11 18:28:46.183	{"StartedAt":"2021-11-11T18:28:46.1661799Z","ServerId":"hfserver2:1792:da519ba1-739c-4802-abc9-71375e71438f","WorkerId":"1bb25050-41db-4ef1-b6db-0a8cddc517ed"}
776993	367888	Processing	NULL	2021-11-12 01:07:50.240	{"StartedAt":"2021-11-12T01:07:50.2384882Z","ServerId":"hfserver1:7180:6c2b5973-ee9e-4670-a0b7-7c079822b8ab","WorkerId":"439b9eda-aa34-4b42-8d54-c509b0b9212a"}

**Comment by kvvinokurov** [comment]
Why does hangfire restart the job without error?

**Comment by kvvinokurov** [comment]
Hangfire runs a scheduled code using Parallel.ForEach with default settings. Could this be the reason that the computer runs out of threads and hangfire stops the execution of the task on one node and starts it on another?

**Comment by odinserj** [comment]
Thanks for reporting this! Yes, unbounded Parallel.For loops without the maximum degree of parallelism could cause this, since keep alive queries in Hangfire.SqlServer use System.Threading.Timer that's based on thread pool. So when thread pool is starved, keep alive queries are not sent for active jobs, and another worker will pick the job, thinking that it was failed.

These queries should be performed in a dedicated thread instead of using the timers, so some changes needs to be made to Hangfire itself to make it more stable under these conditions.

Do you use ParallelOptions.MaxDegreeOfParallelism to limit the number of threads in the Parallel.For loop?

**Comment by kvvinokurov** [comment]
> Thanks for reporting this! Yes, unbounded Parallel.For loops without the maximum degree of parallelism could cause this, since keep alive queries in Hangfire.SqlServer use System.Threading.Timer that's based on thread pool. So when thread pool is starved, keep alive queries are not sent for active jobs, and another worker will pick the job, thinking that it was failed.
> 
> These queries should be performed in a dedicated thread instead of using the timers, so some changes needs to be made to Hangfire itself to make it more stable under these conditions.
> 
> Do you use ParallelOptions.MaxDegreeOfParallelism to limit the number of threads in the Parallel.For loop?

In this case, no.

**Comment by odinserj** [comment]
Thanks for your answer. I'm asking, because bounded Parallel.For will use fixed number of threads, and thread pool in .NET is able to increase the number of available threads. So in this case timer callback invocation shouldn't be delayed so much to cause any troubles. However thread pool is super-busy (due to other calls to Parallel.For for example), timer callback may not be executed in time, causing another worker to fetch the job.

Could you also show me your configuration logic related to Hangfire, especially to the storage?

**Comment by kvvinokurov** [comment]
`
GlobalConfiguration.Configuration
                .UseSqlServerStorage(
                    hangfireDatabaseConnectionName,
                    new SqlServerStorageOptions
                    {
                        CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                        QueuePollInterval = TimeSpan.Zero,
                        SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                        UseRecommendedIsolationLevel = true,
                        PrepareSchemaIfNecessary = true,
                        EnableHeavyMigrations = false
                    }
                );
`

**Comment by kvvinokurov** [comment]
P.S. Hangfire version 1.7.18

**Comment by odinserj** [comment]
@kvvinokurov just want to let you know that version 1.7.28 is released, please see https://www.hangfire.io/blog/2021/12/19/hangfire-1.7.28.html for details. I'm closing the issue, if you still see this problem with SQL Server please open a new issue.
