### ISSUE TITLE
Keep alive select 1 query 

### ISSUE THREAD

**Issue by mertyildiz41** [HangfireIO/Hangfire#1988]
Hello there,

I just wondering something, There is any reason to use `SELECT 1;` command for checking SQL connection?
Is it used because of some kind of connection case?

Also can't be used like this for checking the connection and may open again?

`if (_connection?.State != ConnectionState.Open)
{
    _connection?.Open();
}`

https://github.com/HangfireIO/Hangfire/commit/731765af7577b8c96b94c4f65c9e9b75d4c9348f

**Comment by odinserj** [comment]
The case was to avoid closing a connection by firewall, because in this case associated distributed lock or job transaction will be silently released without any notification. In recent versions they aren't used when [recommended configuration](https://docs.hangfire.io/en/latest/configuration/using-sql-server.html#configuration) is applied – in this case new fetching method that isn't based on transactions and isn't based on a connection state is used.
