### ISSUE TITLE
Question: Has anyone ever tried splitting enqueue and processing up between two different services?

### ISSUE THREAD

**Issue by misterjohannesson** [HangfireIO/Hangfire#2009]
Can Hangfire, in some weird way, support enqueue methods that don't exist or at least don't have an implementation (perhaps interfaces) and with another service process those methods that do have concrete implementations?

I tried creating a visual representation:
![hangfire drawio](https://user-images.githubusercontent.com/17781340/157023582-5161be55-2128-4bc2-92af-03aae578463c.png)

**Comment by tiesont** [comment]
Seems like you're asking two different questions.

To answer what you title is asking, yes, I actually do this right now. I have jobs that are enqueued in an ASP.NET or ASP.NET Core website. The actual background server (the part of Hangfire that actually executes the jobs) is actually split across a few different Windows services (a few of the jobs can be resource intensive, like video transcoding, so they run in their own service). So, yes, enqueueing and executing the jobs can be split.

I suspect that's not what you're asking, based on the text in your issue description. I don't see how _that_ would work. As far as I know, when Hangfire serializes your job into the queue, it serializes the object with the complete namespace. If that *isn't* the case, then in theory you could enqueue the job with a dummy object (a class with an empty implementation) and then just make sure that the background processor only has a reference to the concrete implementation.

Depending on what version of C# you're using, you _could_ have an interface with a default implementation. It was part of the C# 8.0 draft (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods) - I have no idea if it's actually implemented, since I haven't had a use for that feature yet.

**Comment by misterjohannesson** [comment]
We did end up figuring this out.

> If that isn't the case, then in theory you could enqueue the job with a dummy object (a class with an empty implementation) and then just make sure that the background processor only has a reference to the concrete implementation.

So yes, this is it. As long as the Hangfire Server and the service that enqueues Hangfire Jobs have the same namespace, class, and method name, It is easy to share hangfire jobs between jobs.
