### ISSUE TITLE
Azure index recommendation

### ISSUE THREAD

**Issue by IeuanWalker** [HangfireIO/Hangfire#2051]
Azure is recommending the following index to be created - 
![image](https://user-images.githubusercontent.com/6544051/174760267-5a578ccd-c47d-4018-b9e9-a98ae607064d.png)

Says the impact would be high if it was created

**Comment by odinserj** [comment]
Could you show me what schema version you database has for Hangfire? Please tell me what outputs the following query.

```sql
SELECT * FROM [HangFire].[Schema]
```

**Comment by IeuanWalker** [comment]
@odinserj it returned back `5`. 

Hasn't been updated in a few years though

**Comment by odinserj** [comment]
Thanks, could you also tell me what version of Hangfire.Core do you have? I'm trying to understand whether you can upgrade to the latest schema version.

**Comment by IeuanWalker** [comment]
`<PackageReference Include="Hangfire" Version="1.7.10" />`

**Comment by odinserj** [comment]
I would recommend you to [upgrade schema](https://docs.hangfire.io/en/latest/upgrade-guides/upgrading-to-hangfire-1.7.html#migrating-the-schema) to the latest version first (and also upgrade Hangfire to the latest version), because table structure was heavily changed there. Duplicates https://github.com/HangfireIO/Hangfire/issues/844.
