### ISSUE TITLE
High memory consumption in hangfire

### ISSUE THREAD

**Issue by ngaisteve1** [HangfireIO/Hangfire#2114]
I notice that once I started my .NET 6 service which has hangfire (version 1.7.31) in it, its memory usage is 26000 MB. And there are no jobs running or scheduled. This memory usage is seen at Azure App Insights > Live Metrics. Other service, their memory usage are only 400-500 MB.

I tried to use both AddTransient and AddSingleton but the result is the same.

`builder.Services.AddTransient<ITelemetryInitializer, MyTelemetryInitializer>();`
or

`builder.Services.AddSingleton<ITelemetryInitializer, MyTelemetryInitializer>();`

I have also set WorkerCount = 1

```
builder.Services.AddHangfireServer(
    options =>
    {
        options.WorkerCount = 1;
        options.SchedulePollingInterval = TimeSpan.FromDays(1);
        options.HeartbeatInterval = TimeSpan.FromDays(1);
        options.ServerCheckInterval = TimeSpan.FromDays(1);
    }
);
```

**Comment by odinserj** [comment]
The best way to diagnose this issue is to take a memory dump file as [described here](https://khalidabuhakmeh.com/diagnosing-memory-leaks-in-azure-app-services-with-perfview) (don't read "Perfview" paragraph and below) and analyse it with the `dotnet-dump` command as [written here](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak#analyze-the-core-dump). Please post here results of the `dumpheap -stat` command.

**Comment by ngaisteve1** [comment]
Thanks. I think it has nothing to do with hangfire. After I exclude hangfire, my service still shows 28 GB of committed memory. Okay, I will troubleshoot further on this.
