### ISSUE TITLE
Problem with Authorization changes in 1.1.1

### ISSUE THREAD

**Issue by robdmoore** [HangfireIO/Hangfire#214]
Hi,

I've got a problem with the AuthorizationFilter changes from 1.1.1.

I've changed my filter to this signature as per the release notes:

```c#
public bool Authorize(IDictionary<string, object> owinEnvironment)
{
    var context = new OwinContext(owinEnvironment);
    ...
}
```

However, I'm using something like this:

```c#
    context.Authentication.User.IsInRole(AppRoles.Admin.ToString())
```

And `context.Authentication.User` is null when newing up the OwinContext even when logged in (I'm not sure why, but it wasn't before when using 1.0.0).

Thanks

**Comment by andrewthauer** [comment]
I'm also having the same issue with v1.3. However, I think the Authorize method might be executed to early in the pipeline since Request.IsAuthenticated is also returning false. I've tried the following which all return null:

owinContext.Authentication.User
owinContext.Request.User
HttpContext.Current.User

I have custom System.Web.Mvc.AuthorizeAttribute & System.Web.Http.AuthorizeAttribute classes that seem to have no problems getting the appropriate authenticated context. It's just not working in the context of the Hangfire IAuthorizationFilter for some reason. Any ideas?

**Comment by odinserj** [comment]
The order of method calls in `Startup` class matters. Authentication (`app.UseCookiesAuthentication`, etc) methods should be called *before* `UseHangfire` method.

**Comment by andrewthauer** [comment]
@odinserj - Yep, it looks like the order of operations was the problem. Is working correctly now. Thanks.
