### ISSUE TITLE
Update framework to .NET 4.5.1 so that new SQL security updates can be applied.

### ISSUE THREAD

**Issue by conradcn** [HangfireIO/Hangfire#2150]
Hey!

The version of System.Data.SqlClient referenced by Hangfire.SqlServer has a security vulnerability, but cannot be updated because the fixed version requires that the project be on  .NET 4.5.1. It isn't actively exploited in the wild, but probably a good idea to get ahead of it.

Vulnerability Detail: https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMDATASQLCLIENT-3110424

**Comment by Davilink** [comment]
Any update on this ?

**Comment by hoerup** [comment]
All versions before 4.6.2 was EOL'ed by microsoft last year so it doesn't make sense to still support them in hangfire (especially not for new hangfire 1.8)

**Comment by odinserj** [comment]
I'm afraid that issue belongs more to NuGet than to Hangfire and is present in other packages as well, for example, see the following question on Stack Overflow:

https://stackoverflow.com/questions/56727314/nuget-package-manager-does-not-install-package-with-highest-depencency-version

There was the DependencyVersion switch in the early days of NuGet, but I don't know how to use it with `PackageReference` tags. The problem is also described here – https://weblog.west-wind.com/posts/2014/Jun/19/Nuget-Dependencies-and-latest-Versions and there's an issue on GitHub in the NuGet repository that describes this issue in great detail, but unfortunately, I can't find it.

The thing is, Hangfire is an abstraction itself (since it's a framework). It does specify the minimum supported version for its dependencies, and actual versions can be specified (Hangfire will work with any of them) in the target application by specifying those dependent packages explicitly:

```xml
<ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.*" />
</ItemGroup>
```

Unfortunately, if we try to implement this NuGet-based feature in the project itself, we'll be forced to specify only the latest versions almost all of the time, forcing developers into [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) problem, where one package requires one version, and another package requires another version of Hangfire.SqlServer or System.Data.SqlClient.
