### ISSUE TITLE
Hangfire.Pro.Redis huge database and expiration do not work

### ISSUE THREAD

**Issue by Svisstack** [HangfireIO/Hangfire#2162]
Looks like this do not affect successful job expiration which UI says it's still 7 days and causing our redis to be huge.

`GlobalJobFilters.Filters.Add(new CustomExpirationTimeAttribute(TimeSpan.FromMinutes(5)));`

How storage is initialized:

````csharp
services.AddHangfire(x => x.UseRedisStorage("redis-master"));
````

I'm doing something wrong?

**Comment by odinserj** [comment]
Looks like this is due to batches as their job retention is based on the batch itself. Depending on the current configuration, you can decrease the current retention time for background jobs and batches, by default it's 24 hours for background jobs and 7 days for batches and their jobs. After changing configuration value on all of your application instances some time need to be passed for your previous jobs that have previous configuration values to be expired.

```csharp
.UseXXXStorage(/* ... */)
    .WithJobExpirationTimeout(TimeSpan.FromHours(24)) // default value for regular background jobs
    .UseBatches(TimeSpan.FromDays(7)); // default value for batches and their jobs
```

Unfortunately it's not possible to set another expiration time for already created batches and background jobs. However you can monitor memory consumption of your Redis instance and set it's maxmemory-policy configuration value to "volatile-lru" (via the CONFIG SET maxmemory-policy volatile-lru command issued to Redis) when current memory reaches, for example, 75% of available memory threshold. This will avoid OOM exceptions even during peaks, because Redis will be able to expire keys automatically. **However when things back to normal, I'd recommend you to switch the maxmemory-policy to the recommended one value, "noeviction".**

The thing is that "noeviction" policy will help you to keep things under control, you know what to do when max memory condition is hit, and you always have some extra capacity at this point. When you use "volatile-lru" policy all the time you don't have an extra capacity when OOM condition is reported by Redis – because it already removed all the volatile keys at this point.

**Comment by Svisstack** [comment]
Thanks for detailed answer. I confirm that new jobs have correct expiration time after changeing expiration time of the batches.
