### ISSUE TITLE
Hangfire stop recurring jop in Friday, Saturday 

### ISSUE THREAD

**Issue by saidalsaidi** [HangfireIO/Hangfire#2169]
I am facing issue related to recurring jop, it didn't start in Friday and Saturday as the graph 📈 show despite I used Corn.daily(2,0), anyone face this problem?

**Comment by cihatsolak** [comment]
Hi, If your recurring job doesn't start on Friday and Saturday even though you use Cron.Daily(2, 0) the problem may be related to the time zone settings in your application or server. Did you check? Because hangfire uses the server's local time to schedule recurring jobs. Therefore, it is useful to make sure that the server's time zone is set correctly. The time zone may be set incorrectly. Or it may not be a time zone you predicted.

**Comment by saidalsaidi** [comment]
Thanks for your feedback, done 👍🏼✅
