### ISSUE TITLE
The concern of use

### ISSUE THREAD

**Issue by EngRajabi** [HangfireIO/Hangfire#2268]
I was using very old versions of 1.6.*. In an enterprise company. It was set to work with Sql Server.
I had this problem that because the project was very big, it included many jobs, the variety of jobs was also high, and we had many jobs that were executed in several nodes, in 5 seconds.
The problem that happened was that Hangfire caused a very high load on the database, which caused other databases to be affected.
Another problem was that the size of the Hangfire database was very large.
Years have passed since that experience.
I wanted to see if this problem still exists in new versions and net core improvements?
Has there been any thought for the large volume of the database due to many jobs?
@odinserj

**Comment by cezar-pimentel** [comment]
What do you mean by large volume in the database?

The Hangfire application currently running on your company has so many jobs running all day that the SQL Server database behind it gets overloaded?

Can you give us an idea of how many jobs are implemented and running in there?

**Comment by EngRajabi** [comment]
> What do you mean by large volume in the database?
> 
> The Hangfire application currently running on your company has so many jobs running all day that the SQL Server database behind it gets overloaded?
> 
> Can you give us an idea of how many jobs are implemented and running in there?

It's been a long time, I don't remember exactly. But I had almost 100 jobs. After a few months, we received from the database team that the size of the database had increased to about 200 gigs. Apart from the volume of queries, it was also high.
Most of the jobs were executed every 5 or 10 seconds. This caused a lot of log in the database.

**Comment by cezar-pimentel** [comment]
> > What do you mean by large volume in the database?
> > 
> > The Hangfire application currently running on your company has so many jobs running all day that the SQL Server database behind it gets overloaded?
> > 
> > Can you give us an idea of how many jobs are implemented and running in there?
> 
> It's been a long time, I don't remember exactly. But I had almost 100 jobs. After a few months, we received from the database team that the size of the database had increased to about 200 gigs. Apart from the volume of queries, it was also high.
> Most of the jobs were executed every 5 or 10 seconds. This caused a lot of log in the database.
> We had to use the following method to wipe manually, which is not a good thing.
> https://discuss.hangfire.io/t/database-cleanup-sql-server/1318/6
> 
> like: https://github.com/HangfireIO/Hangfire/issues/1705#issuecomment-1059132133

Thanks for your reply.

Yeah, I would say that this "database concern" has more to do with something that the developer / company should address then the library itself.

My jobs also executes a lot of times during the day, and the database can get really big if don't take some action about it.

By default the library keeps the execution records for 24 hours. That is probably a feature that weren't available in the version that you were using. That feature by itself should prevent a lot of database troubles because after 24 hours the record will be purged, unless if you specify a bigger retention time within the library configuration.

For me, I retain all data for 15 days, and after that all the data is stored in a separated decouple database (not connected to hangfire) in case we need to show proof of the processed job.

But, anyways, there's a lot of things you could depending on what you really need to achieve.

**Comment by EngRajabi** [comment]
> 

Thanks
  I will definitely test this
The only question I have is how can I adjust the settings for this time?

**Comment by cezar-pimentel** [comment]
Right here:
![image](https://github.com/HangfireIO/Hangfire/assets/12258489/d033874d-a7fa-4698-845d-31aeb9fbac26)

`_builder.Services.AddHangfire(c =>
{
    c.SetDataCompatibilityLevel(CompatibilityLevel.Version_180)
	...
        .WithJobExpirationTimeout(TimeSpan.FromDays(15))
	...
});`

**Comment by cezar-pimentel** [comment]
Can we close this issue my friend?

**Comment by EngRajabi** [comment]
I am testing. But I close here.
