### ISSUE TITLE
InvisibilityTimeout algorithm ignores server.LastHeartbeat, potentially causing cascading worker stalling

### ISSUE THREAD

**Issue by ses4j** [HangfireIO/Hangfire#227]
http://docs.hangfire.io/en/latest/users-guide/storage-configuration/using-sql-server.html

The referenced docs say that the MS SQL storage engine will reassign a task that is 30 minutes old (by default), on the assumption that the original worker was stopped/killed/died, never to return.  If an errant task infinite loops (or just takes a very long time), this algorithm results in workers being assigned, one-by-one, to the murderous task, and then being effectively taken permanently offline, at a rate of one every 30 minutes.  

The fix seems to be simply to detect this case using the LastHeartbeat.  The server can report its continued existence (maybe with a GUID it invents on startup) and the task(s) it is working on.  (This info would be nice on the "what are my servers doing" web page anyway).

**Comment by odinserj** [comment]
With [1.5.0-beta1](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.0-beta1) release this issue does not make sense anymore. Instead of an algorithm based on InvisibilityTimeout, regular SQL transaction is used to block the processing background job. Fetch SQL query uses the `readpast` hint so other workers simply ignore jobs that are in the processing state.
