### ISSUE TITLE
Determine the queue at runtime

### ISSUE THREAD

**Issue by Atrejoe** [HangfireIO/Hangfire#228]
I would like to define the queue of the task at runtime.

Now there's the QueueAttribute, but it takes a compile-time argument for the queue name.
(I saw that the overload for creating a scheduled task previously had a queue argument, which was removed)

In my case the queues can be defined in a management application which pass throw the same method for scheduling. Something like:

    RecurringJob.AddOrUpdate(
        task.Id.ToString(),
        () => service.Run(task.Id)
        , task.TriggerExpression);

I have different HangFire clients which should only pick up some of the queues (they may be hardcoded).

See the image below: I have some tasks (executables) that are only allowed to be performed on particular clients. Other tasks (Web requests) can normally be performed on any client.

![image](https://cloud.githubusercontent.com/assets/585091/4614670/7c65dd2a-52e2-11e4-8802-fbb751f3679e.png)

The database on the left is our proprietary database, the one on the right is the database containing HangFire.

**Comment by Frudy** [comment]
:+1: 
I also have a scenario similar to this where being able to select the queue at runtime is required.
Adding this possibility would be much appreciated, and enable us to use the otherwise wonderful Hangfire product :-)

**Comment by odinserj** [comment]
Have you seen this solution – http://discuss.hangfire.io/t/one-queue-for-the-whole-farm-and-one-queue-by-server/490/4?u=odinserj?

**Comment by Frudy** [comment]
Hi, thanks for the suggestion.
I tried it out, but it did not solve my problem.

In my scenario we have two independent hangfire servers on the same physical HW that I want to process jobs from two different queues. The key here is that these hangfire servers share DB but not code. So a job scheduled for queue "1" can not be picked up by hangfire server processing queue "2" since they do not share DLLs and thus can not run code for jobs assigned to the other queue. The code is simply not there.

Cheers
/Freddy

**Comment by Atrejoe** [comment]
For me this might work, I actually do have the same codebase at each runner. When I find the time I will try this, thanks.

**Comment by Frudy** [comment]
Hi

I think the solution to my problem could be like:

1) Configure server to process jobs on queue "queue1"
                config.UseServer(new BackgroundJobServerOptions
                {
                    Queues = new[] { "queue1" },
                });
2) Let client schedule recurrent task on "queue1"
            RecurringJob.AddOrUpdate<TaskService>("TaskName", (s) => s.Execute(), Cron.Daily(...), "queue1");
3) Store queue as parameter on job spec. Queue = "queue1"
4) Let server skip jobs that has a queue specified and the queue name does not match those specified for the server.

Cheers
/Freddy

**Comment by odinserj** [comment]
It is possible since Hangfire 1.5.0-beta1 to specify a custom queue for a recurring job. Please see http://hangfire.io/blog/#queues-for-recurring-jobs.

**Comment by Frudy** [comment]
I've tried my scenario (where two independent HF servers, A and B, wants to process two jobs from two different queues, queue A and B) on HF 1.5.2 and it seems to work, but not without protest!

It seems that server A subscribing to jobs on queue A also attempts to load jobs on queue B intended for server B and then HF logs a warning says that it can't load the needed assemblies. This is correct, since server B assemblies do not exist on server A. This generates a lot of warnings in the log files and the dashboard shows this as the recurrent jobs failing.

Anything that can be done?
