### ISSUE TITLE
Queue names longer than 50 characters are cut off

### ISSUE THREAD

**Issue by wertzui** [HangfireIO/Hangfire#2290]
The `Queue` column of the `JobQueue` table only allows for 50 characters.
If a name with more than 50 characters is given, the remaining characters are just cut off by the SQL Server without any exception or warning.
This results in Jobs getting into a queue that no server is listening for, because the servers are listening for the full queue name which might be longer than 50 characters.

**Comment by odinserj** [comment]
Yes, needs some investigation to understand whether it's possible to tell ADO.NET to throw an exception in this case. It will be difficult to validate for a particular length in code, because some applications theoretically can have increased the length, and this would be a breaking change for them. Do you know anything regarding this topic?

**Comment by nklyshko** [comment]
I think this default limit should at least be stated in the documentation.

**Comment by ed-byon** [comment]
Just an FYI - if you're using Azure and you use `Environment.MachineName` to name your queues, be very careful with the [change they just made](https://learn.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-domain?tabs=root%2Cazurecli).  

When this change went into effect, our machine names went from 12 characters to 50+, even though they said existing apps would not be impacted.  All of our jobs ended up in the state described above and we had to requeue them all manually via the UI.

**Comment by odinserj** [comment]
I have fixes this by always throwing an exception, and also using [trace flag 460](https://www.brentozar.com/archive/2019/03/how-to-fix-the-error-string-or-binary-data-would-be-truncated/) on modern SQL Servers to include what actual value has been truncated.

**Comment by drameryan** [comment]
when I call BackgroundJob.Enqueue. I'm getting 
`User 'dbo' does not have permission to run DBCC TRACEON. error`

I'm trying to deploy on Sql Azure and I believe the problem is orginated from this line:

file: src/Hangfire.SqlServer/SqlServerJobQueue.cs

`insert into [{_storage.SchemaName}].JobQueue (JobId, Queue) values (@jobId, @queue) option (querytraceon 460)`

option (querytraceon 460) is not supported by sql azure, and I couldn't find a workaround. Any idea?

**Comment by danroot** [comment]
I'm seeing similar - Sql Azure throws 'User 'dbo' does not have permission to run DBBC TRACEON' even if running with a sa account.  Here is a non-insert query that does similar:

SELECT * FROM HangFire.JobQueue OPTION (QUERYTRACEON 460)

I'm a little puzzled because docs seem to imply it should work for "Azure SQL Managed Instance", but I suspect that is a different SKU from basic Azure SQL Database.
https://azure.microsoft.com/en-us/updates/global-trace-flags-are-now-available-in-azure-sql-database-managed-instance/

**Comment by drameryan** [comment]
I have an update:
If you were using the latest version 1.8.13 downgrade to 1.8.12. I think they first marked as unstable release and later removed from nuget completly.

**Comment by odinserj** [comment]
Thanks for the BTW, this bug will be fixed in 1.8.14 that will be released very soon.
