### ISSUE TITLE
Issue with Hangfire Server Name Display on macOS: Hostname Ignored, GUID Displayed Instead

### ISSUE THREAD

**Issue by ebesavara** [HangfireIO/Hangfire#2351]
I'm facing a minor issue which I encountered when switching work from Windows to macOS. In the project, I use the unpaid version of Hangfire for simple jobs. The problem is that while in Windows, it normally displays the name of the server or PC I'm running it on, on macOS it only gives me a GUID and doesn't take into account the hostname. Is this standard behavior? I use the latest and most current everything.

<img width="846" alt="hostname mac" src="https://github.com/HangfireIO/Hangfire/assets/130746701/3698a67d-cdb4-43d0-a739-8a402d0e72aa">
<img width="821" alt="hostname server mac" src="https://github.com/HangfireIO/Hangfire/assets/130746701/6d74bd54-2ee4-4bc4-a9a5-a3bdbebfb840">

`    builder.Services.AddHangfire(config => {
            config.UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UsePostgreSqlStorage(c => c.UseNpgsqlConnection(builder.Configuration.GetConnectionString("ConnectionString")));
        });

  builder.Services.AddHangfireServer();
`

`app.UseHangfireDashboard("/tasks");`

**Comment by odinserj** [comment]
It is possible to set the `BackgroundJobServerOptions.ServerName` property to `Environment.MachineName` when calling the `AddHangfireServer` method. However, I checked why `Environment.MachineName` property is not used by default, and looks like it was due to the early days of .NET Core, when this method wasn't available in `netstandard1.3`. Since those days are gone, `Environment.MachineName` will be used again since 1.8.8 if other environment variables don't exist.

So you can try to set the server name manually, or just wait for the 1.8.8 release.
