### ISSUE TITLE
Type exists in both Cronos and Hangfire.Core

### ISSUE THREAD

**Issue by khellang** [HangfireIO/Hangfire#2369]
Hello @odinserj! 👋🏻 

We have a project that I recently upgraded to Hangfire.Core 1.8.10 and Cronos 0.8.3.

Somewhere in our code base, we throw a `Cronos.CronFormatException`, but after the upgrade, we're getting this error:

> The type `Cronos.CronFormatException` exists in both `Cronos.dll` and `Hangfire.Core.dll`

Could this be related to the IL merging/repacking? That somehow the type ends up being visible for consumers of `Hangfire.Core`?

**Comment by odinserj** [comment]
Hi @khellang! This is a regression appeared in 1.8.9 after switch to the newer version of ILRepack 2.0.25 - it doesn't internalize classes marked with the `SerializableAttribute` like exceptions by default as previously. Happily, the fix is already available in 2.0.27 so I will dump the dependency and release Hangfire 1.8.11 with the fix.

**Comment by khellang** [comment]
Thank you! I noticed the version was bumped, but I can't see the new version on NuGet. Was it supposed to be released already?
