### ISSUE TITLE
Culture Information changing

### ISSUE THREAD

**Issue by davidnard** [HangfireIO/Hangfire#2482]
- Hangfire.Core version: 1.8.15
- Storage: Hangfire.SqlServer, 1.8.15

We’ve run into an issue in Hangfire versions 1.8.15 and higher, where the CultureInfo settings for worker threads are being modified unexpectedly. Specifically, the PercentDecimalDigits and NumberDecimalDigits properties are altered from their default values (2) to 3, even when the current culture is explicitly set to en-US or another culture where these values are typically 2. This is being seen when a decimal with 4 digits of precision is run through value.ToString("N"). On 1.8.14 and lower, this resulted in 2 digits of precision on the string. Now it appears to be 3.

This behavior is not present in Hangfire version 1.8.14 and below, where the culture settings remain consistent with the application’s global culture configuration.

I can circumvent this by explicitly setting a culture, however I'm wondering if this is a known issue, or if there's a more appropriate way to resolve.
```

public class SetCultureFilter : IServerFilter
{
    public void OnPerforming(PerformingContext context)
    {
       Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
       Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;
    }

    public void OnPerformed(PerformedContext context)
    {
    }
}

```

**Comment by odinserj** [comment]
Thanks for reporting this! There was [a change](https://github.com/HangfireIO/Hangfire/commit/c4b625ab594031b713adb0f56831018cae1245b3) in 1.8.15 that caused Hangfire to use `CultureInfo.GetCultureInfo` method instead of creating a `CultureInfo` instances based on its constructor. However, their semantics are different, because `GetCultureInfo` does not respect user-overridden values set on the OS level:

https://blog.codeinside.eu/2018/05/28/cultureinfo-getculture-vs-new-cultureinfo/

I'm now rolling back the behavior to match the previous one to avoid breaking other installations. The change will be released with 1.8.17.
