### ISSUE TITLE
`RedisConnection.SetRangeInHash` should be able to save `null` values

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#301]
Currently it throws the following exception:

```
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at ServiceStack.Redis.RedisClient.SetRangeInHash(String hashId, IEnumerable`1 keyValuePairs)
```

But sometimes we need to pass `null` values for our keys like in #300. SQL Server implementation handles this case correctly.

**Comment by odinserj** [comment]
Changed milestone to 1.2.0, as it requires to modify ServiceStack.Redis assembly.

**Comment by BoltR** [comment]
I'm curious about what you are planning to do to fix this which requires modifying ServiceStack.Redis. Redis treats everything as a string, and has no concept of null. So while I am not familiar with ServiceStack, I don't know what could be done to the internals in order to change that. Not which couldn't be done elsewhere anyways.

To me there solution are two possible solutions:
- Have a placeholder value that gets converted to/from null before/after it gets inserted/received with Redis. I believe that I will just be modifying StackExchange.Redis version's `ToStringDictionary()`, and `ToHashEntryArray()` extension methods to do this when the time comes to implement this.

- Remove the field from Redis instead of trying to add null at all, and then have Hangfire automatically re-add it as null if it's missing. This will get messy quickly if it's more fields than just LastJobId, and is not something I'd pursue anyways.

**Comment by odinserj** [comment]
Let's ignore this issue.

**Comment by ILONEY** [comment]
I want to  know how to fix this problem?

**Comment by odinserj** [comment]
@ILONEY, how this problem relates to you?
