### ISSUE TITLE
Transactional Remote MSMQ

### ISSUE THREAD

**Issue by maleet** [HangfireIO/Hangfire#333]
There is code in Msmq library:

		transaction.Begin();
                var message = queueIndex == 0
			? messageQueue.Receive(TimeSpan.FromSeconds(5), transaction)
			: messageQueue.Receive(new TimeSpan(1), transaction);

This don't work and code sample from https://johonline.wordpress.com/2012/07/24/msmq-transactional-remote-receive/ could be used as:
               
		messageQueue.Receive(MessageQueueTransactionType.Automatic)

**Comment by odinserj** [comment]
Hey @maleet, thank you for the link. I've also checked some other sources, and you are right. The problem is with transactional receive, it was implemented for remote queues in MSMQ 4.0 (part of Windows Vista and Windows Server 2008 and later). Proposed solution is to fetch messages within a `TransactionScope` instance:

```csharp
using (var scope = new TransactionScope())
{
    var message = _queue.Receive(MessageQueueTransactionType.Automatic);
    // message processing...
    scope.Complete();
}
```

However this `TransactionScope` instance will be propagated to SQL queries as well, and add a lot of blocking. So there is need to think more about implementation.

**Comment by APErebus** [comment]
Just want to leave a comment here to say this is a critical issue for us using MSMQ. It completely removes the ability for us to perform distributed work using Hangfire.

I hope this fix is coming soon.

**Comment by odinserj** [comment]
Hi guys, remote transaction MSMQ queues are supported now in [1.5.0-beta1](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.0-beta1) release :tada:. Thanks to `TransactionScopeOption.Suppress`, the transaction does not affect other SQL queries. Queue paths should have the following format:

```
FormatName:DIRECT=OS:XYZZY\private$\MyQueue
```
