### ISSUE TITLE
Hangfire.GlobalConfiguration type is ambiguous with System.Web.Http.GlobalConfiguration, and pattern is verbose

### ISSUE THREAD

**Issue by tafs7** [HangfireIO/Hangfire#337]
In latest release of Hangfire, a new pattern for configuring options was introduced along with a type named GlobalConfiguration.

This type is ambiguous in name with ```System.Web.Http.GlobalConfiguration```, and should be renamed to a more specific name such as ```HangfireConfiguration```.

Also, I am not sure what the benefit of using a singleton pattern to expose the ```Hangfire.GlobalConfiguration.Configuration```.  It seems extremely verbose.

It would seem to cleaner if we used ```Lazy<T>``` with a better API for configuration...not sure what yet.

**Comment by odinserj** [comment]
This was a pain to choose the name of the `GlobalConfiguration` class and its `Configuration` property. I've tried `HangfireConfiguration`, `HangfireConfig`, `GlobalConfig`, 'Configuration', `Configure`, `ConfigureHangfire`, and many others (I've deleted my list); as well as different property and method names. It took about 4 hours (really!) to make the final decision, and I know it is far from ideal because of WebApi's class with the same name.

But the name is correct, it is really configuration and it is really a global one (there are a bunch of method overloads in Hangfire classes you can use to override the global settings). And in case of collisions there are workaround, such as `Hangfire.GlobalConfiguration` or `using HangfireGlobalConfiguration = Hangfire.GlobalConfiguration`.

Regarding to the `Configuration` property – the main goal is to allow third-party code to add extension methods for it. And I didn't want to use any sort of lambdas, because it is better to avoid them when possible to keep the API cleaner.

However, if you have better suggestion, I'm open to discuss it. It will be strange to include it to 1.x version (unless this is really big problem), but for 2.x it would be better. And I didn't understand you about `Lazy<T>`, can you write more details on it?

**Comment by odinserj** [comment]
@tafs7 what to do with this issue?

**Comment by markalanevans** [comment]
Since it is ambiguous, what do we do?

**Comment by odinserj** [comment]
@markalanevans, just use the fully qualified name. It's in one place, since configuration should be performed on startup. Or use it in a file without the `System.Web.Http` namespace imported. Generally this is not an issue.

```csharp
Hangfire.GlobalConfiguration.Configuration
    .UseSqlServerStorage()
    .UseAutofacActivator();
```

**Comment by markalanevans** [comment]
I went with a separate file. Thanks!
