### ISSUE TITLE
Missing null-check on StorageConnection after casting it to JobStorageConnection

### ISSUE THREAD

**Issue by burningice2866** [HangfireIO/Hangfire#345]
In the Retries-page of the dashboard, there is a missing Null-check, after casting the current connection to JobStorageConnection. This is a problem if one is using a JobStorage which doesn't implement JobStorageConnection but only IStorageConnection

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Dashboard/Pages/RetriesPage.cshtml#L21

**Comment by odinserj** [comment]
@burningice2866, got it! Would you like to make a PR and point it to the `release-1.4.2` branch?

**Comment by burningice2866** [comment]
I'll look at it... can we assume that making an empty JobIds list and pager with 0 records will do the trick?

**Comment by odinserj** [comment]
I think we should show the message "Your storage currently does not support lalala and therefore we can't show this page" or so. Otherwise users may think retries aren't working, and ask a lot of questions on forum. On the other hand, if a pager shows this message for empty retries page (this is usual in normal circumstances), they will be sure retries aren't working. So, only null-check will work here, IMO.

**Comment by odinserj** [comment]
Hi @burningice2866, any news? I'm planning to release this bug fix in 1.4.2.

**Comment by odinserj** [comment]
Added the following message:

![image](https://cloud.githubusercontent.com/assets/1078718/7492388/545e8a38-f400-11e4-9c54-2e0865ccd64c.png)
