### ISSUE TITLE
After a publish in my host, hangfire server not working

### ISSUE THREAD

**Issue by senthilsivanath** [HangfireIO/Hangfire#347]
![image](https://cloud.githubusercontent.com/assets/1016068/7337572/8051e0e2-ec4c-11e4-8d6f-6c546fb17482.png)

This has been the issue for quite few days, server change is not detected for some time.

Have been using shared hosting for the app, on every remote publish the app gets deployed to different virtual server and the old server is no more. Hangfire, takes a long time (more than 20 mins - 1 hour) to detect new server and process the jobs.

Is it possible for hangfire to recheck the servers from dashboard, can we add this as a feature ? Using Hangfire 1.4

**Comment by odinserj** [comment]
Recheck feature isn't possible, because "Started" and "Heartbeat" metrics work quitely differently than you think. Each `BackgroundJobServer` instance (responsible for background job processing) every 5 seconds executes a query to your job storage (perhaps SQL Server in your case) to update the corresponding server entry. Dashboard only displays the current information.

If a background job server can't update records like in your case, it is very likely that there are issues with your storage instance – network or other connectivity problems, etc. Please [attach logs](http://docs.hangfire.io/en/latest/configuration/configuring-logging.html) to this issue to see the exceptions Hangfire receives.

**Comment by odinserj** [comment]
@senthilsivanath, if you have any news, please re-open this issue.
