### ISSUE TITLE
SqlServerStorageOptions.QueuePollInterval is ignored in console application

### ISSUE THREAD

**Issue by andersrosten** [HangfireIO/Hangfire#359]
SqlServerStorageOptions.QueuePollInterval is working fine when running the Hangfire server inside a website, but in my console app the interval is ignored and the default of 15 seconds is used.

In the Main method of the console app all i do is the following:

			var options = new SqlServerStorageOptions
			{
				QueuePollInterval = TimeSpan.FromMilliseconds(10)
			};
			
			GlobalConfiguration.Configuration.UseSqlServerStorage(..., options);

			using (var server = new BackgroundJobServer())
			{
				Console.WriteLine("Hangfire Server started. Press any key to exit...");
				Console.ReadKey();
			}

**Comment by odinserj** [comment]
Millisecond-based intervals aren't supported. I've updated [the docs](http://docs.hangfire.io/en/latest/configuration/using-sql-server.html#configuring-the-polling-interval) to highlight this fact. Instead of stressing your storage with such a high number of queries consider using Hangfire.SqlServer.Msmq.

**Comment by odinserj** [comment]
Closing the issue. Please feel free to re-open it if you have any other questions related to the topic. However, it is better to ask them on the forum.
