### ISSUE TITLE
Owin Cast Exception When Project Is Using Microsoft.Owin 3.0.1

### ISSUE THREAD

**Issue by ranstett** [HangfireIO/Hangfire#386]
I have a project that is using the UseWsFederationAuthentication to authenticate against Azure AD. It requires Microsoft.Owin 3.0.1. I verifiied the authentication was working, I then added Hangfire and the Dashboard to the project through Nuget. When I would go to the Dashbaord and try to execute something I would get the following error. 

System.InvalidCastException: Unable to cast object of type 'Microsoft.Owin.FormCollection' to type 'Microsoft.Owin.IFormCollection'.

After reviewing the stack trace it appeared it wasn't in the Hangfire code, so I downloaded the GitHub package and updated the Microsoft.Owin Nuget Package to the 3.0.1 (latest), I built the project and swapped out the DLLs, then everything started working.

**Comment by tombrant** [comment]
Which version of Hangfire did you download and update?  Was it the latest 1.4.3?

**Comment by ranstett** [comment]
I had installed 1.4.3 and this issue was present. I committed a version of 1.4.3 (https://github.com/ranstett/Hangfire/commits?author=ranstett) with the updated OWIN. I'm using it in a production environment now and haven't had any problems.

**Comment by odinserj** [comment]
Hi guys, sorry for the loong-loong delay :( I've just released Hangfire 1.4.4 with fix for this issue. Hangfire 1.4.x still uses Microsoft.Owin 2.1.0 (otherwise previous user get this error), but don't use the cached form collection now, re-reading the form. Hangfire 1.5.0 will come with the new Microsoft.Owin, however I'll keep the hack to save users who use Microsoft.Owin 2.1.0.

**Comment by odinserj** [comment]
There is a bug in 1.4.4, if you installed it today, please upgrade to 1.4.5 :frowning:
