### ISSUE TITLE
Port hangfire to Sqlite

### ISSUE THREAD

**Issue by bgiromini** [HangfireIO/Hangfire#388]
I have seen both Postgres and Oracle implementations but didn't know if anyone would be interested in a Sqlite version. This would make using Hangfire in a Windows service more self-containted with no outside dependencies.

**Comment by vip32** [comment]
the hangfire sqlserver storage is using dapper for its data access. dapper also supports sqlite, so this should be easy to implement. with this setup you can run an embedded database.

only change is to use the SqliteConnection instead of SqlConnection, define the SqliteOptions and maybe modify some queries.

**Comment by vip32** [comment]
i have started on a SQLite storage package. https://github.com/vip32/Hangfire/tree/master/src/Hangfire.SQLite

**Comment by bgiromini** [comment]
@vip32 Let me check it out.

**Comment by AGRocks** [comment]
Hi @odinserj, 

Was this one merged or just parked for now? There's no commits on @vip32 SQLite fork.
The NuGet package [Hangfire.SQLite](https://www.nuget.org/packages/Hangfire.SQLite/) is also pointing to the different source so would be great to update docs so that there won't be confusion.

Cheers

**Comment by vip32** [comment]
i haven't been able to finish the sqlite fork, not sure if it will ever finish. however a rough 80% should be in there now...

**Comment by Serjster** [comment]
This is a finished implementation, is it not? https://github.com/wanlitao/HangfireExtension/tree/master/Hangfire.SQLite

**Comment by vip32** [comment]
Haven't seen that one before.  It is on nuget https://www.nuget.org/packages/Hangfire.SQLite
Did you try it out already?

**Comment by AGRocks** [comment]
@vip32 actually repo by @wanlitao is source for **Hangfire.SQLite** nuget package.

@Serjster Unfortunately **SQLite** can't be used as a **Hangfire** persistence _db_. At least fully functional. I tested 1 Worker per queue which works fine. When it comes to having more then one worker concurrency issues occur.

**Comment by vip32** [comment]
that's interesting as sqlite is able to handle multiple threads, maybe an issue with the sql statements?

**Comment by AGRocks** [comment]
@vip32 maybe there are. check @wanlitao's repo. I'm not aware of any kind of database(file)-wide lock in **SQLite** which will prevent different workers to pick same job.

**Comment by stajs** [comment]
Hangfire + SQLite is in a very confusing state. As noted above, the [official extensions page](http://hangfire.io/extensions) adds to this confusion. It lists @vip32 as the author of the GitHub project [Hangfire.SQLite](https://github.com/vip32/Hangfire.SQLite), but the page templating makes the faulty assumption that the GitHub project name and the NuGet package are the same:

```
<a href="https://www.nuget.org/packages/{{ project.name }}/" target="_blank">
```

This results in linking to an entirely different [Hangfire.SQLite](https://www.nuget.org/packages/Hangfire.SQLite/) NuGet package, backed by a [different GitHub project](https://github.com/wanlitao/HangfireExtension) by @wanlitao. I can't find a NuGet package based on @vip32's work.

Based on comments above and elsewhere, can I assume that SQLite storage is not production-ready?

[@odinserj said](https://discuss.hangfire.io/t/hangfire-with-out-sql-server/1194):

> Yep, there are Hangfire.SQLite and Hangfire.MemoryStorage, but I haven't tested them.

[@vip32 said](https://github.com/HangfireIO/Hangfire/issues/388#issuecomment-163890607):

> i haven't been able to finish the sqlite fork, not sure if it will ever finish. however a rough 80% should be in there now...

[@AGRocks said](https://github.com/HangfireIO/Hangfire/issues/388#issuecomment-178776776):

> Unfortunately SQLite can't be used as a Hangfire persistence db. At least fully functional. I tested 1 Worker per queue which works fine. When it comes to having more then one worker concurrency issues occur.

**Comment by AGRocks** [comment]
@stajs as far as I know its not. And considering supported nosql solutions it probably won't be ever prod ready.

**Comment by stajs** [comment]
@AGRocks Good to know, thanks.

**Comment by vip32** [comment]
maybe it makes sense to just remove the links to these sqlite packages, at least mine is not finished or in a production ready state. alpha at least (due to lack of testing with concurrency and so). it should now be clear from the [readme](https://github.com/vip32/Hangfire.SQLite/blob/master/README.md) at least. also made PR to remove it from the extensions page. hope this makes things clear.

**Comment by stajs** [comment]
Thanks, I appreciate the clarity.

**Comment by rocker8942** [comment]
I wrote a blog on how to use SQLite, http://www.moneystock.net/wp_e/2016/12/03/use-hangfire-with-sqlite-in-asp-net-4-5/. Hope this help.
