### ISSUE TITLE
LGPL license

### ISSUE THREAD

**Issue by gbarker** [HangfireIO/Hangfire#446]
We'd love to use Hangfire.  But LGPL is a deal breaker.  Not because we are malicious exploiters.  But because it's too complicated and we can't be 100% sure we couldn't be sued.  Is it really necessary?

**Comment by marcoCasamento** [comment]
+1. 
Definitely not an expert on the topic but always felt like LGPL is confusing at best. And I must also produce useless documentation about how to replace the dll to customer who'll never read, but they could potentially sue me if I don't. 
Well, I love the product and I'll use it nevertheless, but yes, MIT would be... definitely less "infectuous"

**Comment by odinserj** [comment]
I totally agree with you, guys. I chosen LGPL due to paranoid reasons, that someone will take the software or its part and release another background processing framework. I felt more secure with this license at the very beginning, despite this fear is ridiculous and absurd. I really wanted to see another background processing framework in .NET, but didn't want to compete with myself.

Nevertheless, a while ago I began to think about changing the license to MIT too, but I'm not in a hurry to do this step, at least before 2.0.

**Comment by gauravspatel** [comment]
It's been a few years now.  Any chance of a switch to MIT now?  

It would really help us folks stuck in corporations where LGPL is an auto-no.

**Comment by ferreirix** [comment]
Another year has passed by. Is it ever going to change or better forget it?

Thanks

**Comment by marsop** [comment]
I would still be interested in this… as mentioned before, for some kind of applications this is sadly still a no-go.
