### ISSUE TITLE
Hangfire does not work under dnxcore50

### ISSUE THREAD

**Issue by darcythomas** [HangfireIO/Hangfire#476]
Hangfire does not work under dnxcore50 .Net Core

To replicate:
New MVC5 beta8 project
Nuget: Install-package hangfire
Build <- fails

**Comment by odinserj** [comment]
Hangfire doesn't support .NET Core framework yet. I've made some investigations under the `dnx` branch (it is a playground, and nothing else), and found some things that should be done:

* All the dependencies should support .NET Core too. Some already support it, but there is a burden in package versions.
* Dashboard should be abstracted away from OWIN to support both OWIN and new HTTP abstractions, since Microsoft.Owin package that is heavily used does not support DNX (I'm in doubt that it will support DNX).
* Build scripts should be either modified, and it is interesting for me how to plug in ILMerge here.

**Comment by yngndrw** [comment]
Regarding ILMerge, please see this thread:
https://github.com/aspnet/dnx/issues/819

A long read (I only skimmed it), but it does look like there will be first-class support for merging in dependencies in the new system. It's still in the design stage so it might take a while to be realised, however.

**Comment by odinserj** [comment]
Yep, I'm keeping an eye on this, and built-in support for internalizing would be awesome. But it is not implemented yet. Hope this will be available before ASP.NET 5 RTM.

**Comment by stajs** [comment]
FWIW, it does work under dnx46 beta8.

@odinserj I'm confused by your comment about the Dashboard, have you changed your mind [from this previous comment](https://discuss.hangfire.io/t/how-to-config-hangfire-with-asp-net-5/945/10)? Of course, no problem in changing your mind and great news if there is a better method to integrate with dnx. And as I said, it is working great under dnx46 beta8 so far :dancer: by using [your code snippet](https://discuss.hangfire.io/t/how-to-config-hangfire-with-asp-net-5/945/3) and referencing [Microsoft.AspNet.Owin](https://discuss.hangfire.io/t/how-to-config-hangfire-with-asp-net-5/945/11).

**Comment by odinserj** [comment]
> FWIW, it does work under dnx46 beta8.

Yep, because it is based on full framework.

> @odinserj I'm confused by your comment about the Dashboard, have you changed your mind from this previous comment?

Yes, I was wrong. Dashboard code is heavily based on Microsoft.Owin, that does not support .NET Core. There are two ways – port Microsoft.Owin to .NET Core or use new abstractions. IMO it is better to choose the latter.

**Comment by odinserj** [comment]
.NET Core support is almost here, see #604 :tada:
