### ISSUE TITLE
Disable Hangifre deffer during Debug.

### ISSUE THREAD

**Issue by ppumkin** [HangfireIO/Hangfire#488]
Currently if I have code on development machine with use of Hangifire, but the server is not running the code will fail.

Is it possible to put in a setting maybe, to execute the code normally without shooting it out to hangfire server. Just as if hangfire was not even used at all?

**Comment by gandarez** [comment]
I didn't understand what you need. 
Do you wanna debug at the same time server catch it up?

**Comment by ppumkin** [comment]
Sorry, I dont know what its called properly. Inlining the execution?

Currently, if I am developing, I need to have hangfire configuration setup, to a staging server or live or debug or all. Depends what I am doing, debugging or viewing stats.

When I need to test new integration, I don't want to use hangfire, because other developers may be using the same debug connection and its firing on their machines, or on staging server but never on MY machine.

So I have to do this.

![image](https://cloud.githubusercontent.com/assets/1249683/11683462/dacf919a-9e62-11e5-8c2d-259d27339e7b.png)

It would be fantastic to have a setting, execute in-line ON MY MACHINE. Even if hangire is executed. I rather change one setting on hangifire than comment and uncommented multiple lines of code just to test locally without shooting out to hangfire.

**Comment by stajs** [comment]
This "inline execution" thing is a bit weird. Why do you want to "execute the code normally without shooting it out to hangfire server"?

Attempting to understand your situation, it seems that you don't run a Hangfire server when developing.... if so, why not? You mention "because other developers may be using the same debug connection", does this mean all developers are using the same database? Well, there's your problem. Just run against a local database; connection strings are easy to swap out when developing.

If you _really_ want to do it, there are a couple of things you could try, but I **really don't recommend** because they are ugly and brittle:

- You could define a compiler constant and `#ifdef` around those bits of code you commented out.
- Instead of calling Hangfire directly, have some sort of helper class that checks a setting to know whether to enqueue the expression to Hangfire or turn the expression into a method invocation.

IMHO if you want to ensure you aren't queuing jobs to a shared system, you should be developing against a local database.

**Comment by stajs** [comment]
As for this:

>  execute it immediately so I can debug it step by step as normal

... you can debug in to your method call as normal, once Hangfire picks up and processes your job. If you have a requirement for immediate execution, it probably shouldn't be handed off to Hangfire.

**Comment by ppumkin** [comment]
Yea, I suppose doing a local sql express will solve this problem.

The issue was a shared db was checked in to TFS and all devs were using it. Random things we firing away on random PC's.

**Comment by stajs** [comment]
That sounds... horrible....!

**Comment by ppumkin** [comment]
It doesn't just horrible.. it is horrible. 
Even more horrible is managing connection strings in web.config with TFS, so its its a duo of horrible.

Works great on staging and live though.. just making development more painful as stepping though linear code is more logical and faster than waiting for hangifre to call back with some delay. Thats all.

**Comment by odinserj** [comment]
@ppumkin, you can use [Hangfire.MemoryStorage](https://github.com/perrich/Hangfire.MemoryStorage) for testing purposes. Or create a wrapper around Hangfire that will call expressions when you need, you can look at expression compiler in the sources. Hangfire is all about background, no plans to add a feature that breaks the basic principle.

**Comment by stajs** [comment]
@ppumkin 

> faster than waiting for hangifre to call back with some delay

If you use SQL Express, with MSMQ, jobs are picked up almost instantly.
