### ISSUE TITLE
GlobalJobFilters.Filters Duplicated values

### ISSUE THREAD

**Issue by gandarez** [HangfireIO/Hangfire#497]
Hi,
When adding an existing filter to global list it simply repeats the class instead of replacing it. Is it a problem? Wouldn't be nice to replace based on the class and make it unique?

```C#
GlobalConfiguration.Configuration.UseSqlServerStorage("Hangfire",
                new SqlServerStorageOptions
                {
                    QueuePollInterval = TimeSpan.FromSeconds(AppConfig.GetInt32("QueuePollInterval", 5))
                })
                .UseFilter(new AutomaticRetryAttribute
                {
                    Attempts = AppConfig.GetInt32("AutomaticRetryAttempts", 3)
                });
```

![image](https://cloud.githubusercontent.com/assets/782854/12300324/146695ce-ba02-11e5-879f-fd8e01973894.png)

**Comment by odinserj** [comment]
This is not a problem. Behavior is the same as in ASP.NET MVC filters – the latest filter will be used, because at the moment of getting the list of filters, [duplicates are removed](https://github.com/HangfireIO/Hangfire/blob/44abf9f78e0b49410b602a4a8f3b36bcdbf91ac2/src/Hangfire.Core/Common/JobFilterProviderCollection.cs#L56).

**Comment by gandarez** [comment]
Thanks!

Please close this "issue".
