### ISSUE TITLE
Potential performance issues - hot path in Hangfire.SqlServerConnection.FetchNextJob

### ISSUE THREAD

**Issue by krzysztof-at-mp** [HangfireIO/Hangfire#585]
I run some tools to check our application performance. The tool found that the most expensive path is the Hangfire.SqlServerConnection.FetchNextJob. ![hangfire_hot](https://cloud.githubusercontent.com/assets/19307847/15705602/697b9c9c-27f0-11e6-84ee-43c03d4b0342.png)

Is this a known issue? Are there any fixes/workarounds which might be used?

**Comment by odinserj** [comment]
This is the nature of polling – check for new jobs, wait a while (defaults to 15 seconds), repeat. If there are no jobs, then Hangfire Workers will issue a lot of `WaitOne` calls causing the results above to appear, because the profiler sees that the `Dequeue` method is running more than 15 seconds (or even more).

You can use *Thread cycle time* time measurement for profiling to measure time only when threads are running (as opposed to *Real time*). Or create some more background jobs to make it busy.
