### ISSUE TITLE
AutomaticRetries attribute not read from IoC injected classes.

### ISSUE THREAD

**Issue by MikeFoden** [HangfireIO/Hangfire#597]
When using dependency injection, the class inheriting an interface's attributes won't get read and acted upon.

Case in point if my class is as follows:

```
public class ExampleJob: IHangfireJob
    {
        private readonly ILog _logger;

        public ExampleJob(ILog logger)
        {
            _logger = logger;
        }

        [AutomaticRetry(Attempts = 5)]
        public void Start()
        {
        }
    }
```

The attribute won't be read. If it's applied directly to the Interface it will, but not on the implementation of the interface.

**Comment by ogborstad** [comment]
Yeah, I fell into this trap as well, as have others:

https://discuss.hangfire.io/t/disableconcurrentexecution-bug/866

**Comment by odinserj** [comment]
It is not possible for a class to "inherit" attributes from an interface. Keep in mind that a class never inherits an interface, it only implements it. The inherit parameter will work if the property is defined on a parent class with the attribute applied, but not if it is on an interface.

Any time you implement an interface, you must re-apply the attributes which you want to apply for this specific instance of the class. If you have to inherit the attributes, you should use an abstract base class instead of an interface.
