### ISSUE TITLE
Counts not updated

### ISSUE THREAD

**Issue by GioviQ** [HangfireIO/Hangfire#632]
Jobs after a while are deleted, but counts not
![succeeded jobs hangfire](https://cloud.githubusercontent.com/assets/7103057/17333576/3c8d3ccc-58d3-11e6-9b0c-f81066c296a1.png)

**Comment by odinserj** [comment]
Succeeded and Deleted counters are detached from the corresponding background job existence, because jobs in these states become expired after 1 day since the state transition. These counters should show the actual numbers, disregarding of presence or absence of background jobs.

So, read this as two background jobs were succeeded, but were expired to not to blow up your storage.
