### ISSUE TITLE
Make IX_HangFire_JobParameter_JobIdAndName index unique

### ISSUE THREAD

**Issue by odinserj** [HangfireIO/Hangfire#658]
That index is unique in mind, but not currently. It should be re-created with a new name `UX_HangFire_JobParameter_JobIdAndName` in a migration file `Install.sql` (other files are auto-generated using this file). Database version should also be bumped in the install script, and in the `SqlServerObjectsInstaller` class.

**Comment by aidmsu** [comment]
@odinserj it looks like #898 fixes this issue 😄

**Comment by taqabubaker** [comment]
Hi @odinserj,

Is this issue still open? because @aidmsu reply confused me 😕

Anyway in case it is still opened I would like to contribute. The only issue I have that I'm not sure how or where to write the unit test for this issue, since HangFire will update the value of the parameter in case the 'Name' (i.e. parameter name) already exists, right?

So shall I write a pure SQL statement as a unit test?

Sorry for the long comment.
