### ISSUE TITLE
Job server started on multiple pools

### ISSUE THREAD

**Issue by fredgate** [HangfireIO/Hangfire#665]
We met a serious issue when deploying our ASP.net web application on a integration server.
The IIS on server host multiple applications pool and multiple web applications. We are deploying only one web application with a embeded hangfire server. We follow the recommendations from this page : http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html

Deployement is ok, but when we go to the dashboard, we see that there is not one server that is running but four servers ! The number in the server name is the identifier of the process hosting the server.
One Hangfire server is executed on the good application pool, but also on three others applications pools ! There was 6 running applications pools.
If I stop and restart the pool of my application, the Hangfire is well restarted (whitout creating additional server). If I stop one of the 3 others application pool, one Hangfire is also stopped.
This is very curious and worrying that a Hangfire server can be executed on the application pool of others web applications.

Some screenshort of this case :
![hangfire-dashboard](https://cloud.githubusercontent.com/assets/3648269/18432893/fa464afc-78e4-11e6-9961-44bd8e7e140e.png)
![hangfire-w3wp](https://cloud.githubusercontent.com/assets/3648269/18432964/45b02616-78e5-11e6-96d0-aa25371f57e0.png)

May be a important point : the deployment is automated using Powershell / DSC. During this deployment, a DSC resource updates (if necessary) the applicationHost.config file of IIS.

**Comment by odinserj** [comment]
Duplicates #457, please see the https://github.com/HangfireIO/Hangfire/issues/457#issuecomment-235962852 answer. In short, there is a bug in ASP.NET, when we turning the autostartproviders feature on – appdomain may be created multiple times during the deploys, and no events will trigger on shutdown for that appdomains, because they aren't fully started yet, and will never be started. And we have no better alternative for auto-starting an application. 

I've created [`Hangfire.AspNet`](https://github.com/HangfireIO/Hangfire.AspNet) for handling this issue.
