### ISSUE TITLE
.net core rc2 and Hangfire 1.6.5

### ISSUE THREAD

**Issue by nishantsgs** [HangfireIO/Hangfire#681]
I am using "Microsoft.NETCore.App": { "version": "1.0.0-rc2-3002702"} along with Hangfire 1.6.5. I am getting  Error Msg:-

The call is ambiguous between the following methods or properties: 'Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseContentRoot(Microsoft.AspNetCore.Hosting.IWebHostBuilder, string)' and 'Microsoft.AspNetCore.Hosting.HostingAbstractionsWebHostBuilderExtensions.UseContentRoot(Microsoft.AspNetCore.Hosting.IWebHostBuilder, string)'

if i remove HangFire reference project is running properly. Can you please help.

**Comment by pieceofsummer** [comment]
It doesn't look like it has something to to with Hangfire: https://github.com/aspnet/EntityFramework/issues/5884

Most likely your packages are a mess right now, because you're using not even `rc2-final` but some specific build. Probably after `dotnet restore --no-cache` you'll get even more issues :)

And with `1.0.1` released somewhat ago, I don't see any good reasons to not update.
