### ISSUE TITLE
Replace, not add, queue providers

### ISSUE THREAD

**Issue by barclayadam** [HangfireIO/Hangfire#716]
We use Azure Service Bus instead of the built in SQL storage queue provider. I'e just been profiling application and noticed an amount of time being spent in `SqlServerJobQueueMonitoringApi.GetQueues`, partly I believe because of the locking.

At the moment it is not possible (from what I can tell) to completely remove this queue provider. Is there a reason for this, or could it be possible to open up `QueueProviders` /  `PersistentJobQueueProviderCollection` to allow for the removal of existing providers? 

Over a time period of around 2 minutes I see 28,680ms of time spent just in this method (with the dashboard open), so a nice win to completely remove

**Comment by odinserj** [comment]
Hm, I don't like that there is a collection of queue providers at all, looks like an overengineering. But we can't remove the collection without producing breaking changes. Instead, we can add the `DefaultProvider` property to the `PersistentJobQueueProviderCollection` class, since the "default provider" entity is already present in that class.

Would you like to make a PR for this?

**Comment by barclayadam** [comment]
I'll take a proper look at this and see what I can do. Are you suggesting that having a collection of queue providers is to be discouraged, to instead have a single one exposed that can be replaced? So the collection becomes `DefaultProvider` + other added ones to maintain backwards compat whilst allowing the replacing of this default?
