### ISSUE TITLE
Change RecurringJob class to non-static

### ISSUE THREAD

**Issue by icsharp** [HangfireIO/Hangfire#795]
I want to do some method extensions with Hangfire class `RecurringJob`, but `RecurringJob` is static class.
It almost did not affect if changing  `RecurringJob` to non-static I thought.

**Comment by burningice2866** [comment]
`RecurringJob` is a facade/service class which doesn't represent anything by itself. You never have an instance of it, it simply provides utility methods to with a `RecurringJobManager`. So even by making it non-static, you would never instantiate it, and would therefor never have a change to call your extension methods.

One could argue that the `RecurringJobManager` should be exposed and you could add your extension methods to it since its an instance.

https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/RecurringJob.cs#L27

**Comment by burningice2866** [comment]
Looking more at the source, `RecurringJobManager` is simply a service-wrapper around the `JobStorage`, so there is nothing wrong with instantiating a new `RecurringJobManager` whenever you need to Add or Trigger a new recurring job and just add your extension methods directly to it.

**Comment by odinserj** [comment]
There is [`IRecurringJobManager`](https://github.com/HangfireIO/Hangfire/blob/6d155631beb7800f2bdf34a0bbaeb1af48a0a298/src/Hangfire.Core/IRecurringJobManager.cs#L22) interface, and there is [`RecurringJobManager`](https://github.com/HangfireIO/Hangfire/blob/6d155631beb7800f2bdf34a0bbaeb1af48a0a298/src/Hangfire.Core/RecurringJobManager.cs#L32) class, so you could add as many extension methods as you want ☺️

**Comment by icsharp** [comment]
@burningice2866 @odinserj 
Thanks so much, I got it!
