### ISSUE TITLE
Dashboard background polling does not handle 401 responses

### ISSUE THREAD

**Issue by prochnowc** [HangfireIO/Hangfire#861]
We have implemented our own authentication using OpenID connect. Everything works fine except:
When authentication session is lost (could not refresh auth token because e.g. was revoked) the dashboard does not correctly handle "HTTP 401" responses when polling .. it simply keeps polling forever.

**Comment by prochnowc** [comment]
@odinserj  Any comments?

**Comment by dalini** [comment]
We have some issues because of this behavior, some hints how to avoid or handle the situation, or if and when an improvement related to this topic is planned, would be great. Thanks in advance.

**Comment by odinserj** [comment]
Guys, what do you think dashboard should do instead of polling with the same interval?

**Comment by prochnowc** [comment]
Good question. At least it should stop polling if unauthenticated/unauthorized is returned.
Maybe dashboard should show some error message which instructs user to reload page, or something like that.

**Comment by odinserj** [comment]
Sounds good, maybe we should place a yellow alert box with the corresponding information and button to reload the page in case of an "unauthorized" response just before [`RenderBody`](https://github.com/HangfireIO/Hangfire/blob/332ea492cf61d3d13e4a7f64455a61bbae2c660c/src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml#L53) call. Would someone like to implement this?

**Comment by k3davis** [comment]
@odinserj We're using a custom IDashboardAuthorizationFilter (as described in the docs) to handle authentication to the dashboard. In that case, since the "parent app" (for lack of a better term) doesn't have any special error handler, the page returned to the user is blank (and a 401 in the background which you can see via Fiddler). It doesn't seem like in this situation the views are being displayed at all, so I don't see how we can add an alert box. Perhaps I'm misunderstanding the suggestion or other things have changed since this was suggested.

I would love a way for Hangfire to visually display unauthorized status, or provide an optional redirect point (such as to the app's login page). But to the underlying point of this issue it doesn't make sense for it to poll continuously when it is unauthorized.

On a side note, can this status polling be tuned down? I've set longer values for QueuePollInterval, SchedulePollingInterval, and HeartbeatInterval, none of which seem to affect the timing of the /hangfire/status polling.

Thanks for your input.

**Comment by prochnowc** [comment]
@odinserj  Ping. Can you please have a look at my referenced PR ? Any chances that this can be integrated into next version?
