### ISSUE TITLE
Hangfire.ProRedis 2.1.0 crashes debugger on VSCode on OS X

### ISSUE THREAD

**Issue by jenyayel** [HangfireIO/Hangfire#875]
Hi,

The debugger of VSCode crashes/disconnects with the message below when the package `Hangfire.ProRedis 2.1.0` installed:
![screen shot 2017-04-25 at 10 55 36 am](https://cloud.githubusercontent.com/assets/1775602/25374359/cae6dffc-29a5-11e7-8ae2-fe1a21be7b02.png)

You don't even need to call method `AddHangfire`. Once you downgrade to `Hangfire.ProRedis 2.0.6` the problem not happening. 

It was tested on multiple Macs. I've created a project which reproduces  this [here](https://github.com/jenyayel/hangfire-pro-redis-bug-osx). It is a minimal asp.net core project with hangfire installed (the same reproduced with earler versions of .NET SDK's, e.g. `project.json`). 

It doesn't happen on Windows with same versions of VSCode (1.11.2) and .NET SDK.

CC @eugene-senexx

**Comment by odinserj** [comment]
Hm, that's very interesting. I've migrated to the new csproj format in Hangfire.Pro.Redis 2.1.0, maybe this change causes the issue. I'll bring MacBook to my office tomorrow to investigate the problem.

**Comment by odinserj** [comment]
DebugType: embedded caused this behavior, Hangfire.Pro package is also affected. I've just released [Hangfire.Pro.Redis](https://www.hangfire.io/blog/2017/04/27/hangfire.pro.redis-2.1.1.html) with the fix, for Hangfire.Pro I'll wait a bit. `embedded` debug type was switched to `portable`, it's more correct, because the first one is related to sourcelink 2.0 support. Thanks for reporting!
