### ISSUE TITLE
Get job id of added "RecurringJob"

### ISSUE THREAD

**Issue by Behzadkhosravifar** [HangfireIO/Hangfire#886]
Hi,

I know the `RecurringJob.AddOrUpdate` method set my custom __job id__ to recurring jobs but _hangfire_ values for __job id__ is very good and enough for me and just I want to get that like `BackgroundJob.Schedule` method. 
In the other words, I would like to write my below code:

```cs
var jobId = RecurringJob.AddOrUpdate(() => Console.WriteLine("Recurring!"), Cron.Daily);
```

Thanks a lot

**Comment by burningice2866** [comment]
How exactly should this work? There will even be an infinite number or jobs being enqueued so which of them do you expect to get the id from?

`BackgroundJob.Schedule` can return you a jobId since only one job will be created based on that call. `RecurringJob` will keep and keep and keep enqueuing the job, each time with a different jobId.

**Comment by Behzadkhosravifar** [comment]
RecurringJob Each time with a different jobId!

Thanks you.
