### ISSUE TITLE
RecurringJob doesn't triggers!

### ISSUE THREAD

**Issue by dvladimirovich** [HangfireIO/Hangfire#892]
![succeeded jobs hangfire](https://cloud.githubusercontent.com/assets/13225337/26270623/04e9738c-3d05-11e7-8d0f-a4283788051c.jpeg)
Hi I've normally configured Hangfire with my ASP.NET MVC 5 web application. I've added a recurring job and set CRON 2 hours:
`RecurringJob.AddOrUpdate<IScheduleService>(jobId, scheduler => scheduler.ScheduleMultiPricesInfo(1), Cron.HourInterval(2));`
Unfortunately, it doesn't triggers every time. Here I've added screenshot where you can see big period of non trggering. As far as I know IIS configured to start automatically... And one else is that surprisingly 3rd and 4th triggering differs only with one hour, but as I've mentioned I created it with `Cron.HourlyInterval(2)`.
Why it happens?

**Comment by aidmsu** [comment]
Hi @dvladimirovich!

1. It looks like your application was going to sleep at some point. It's not enough to enable automatic start-up for IIS. You should also make application always running. Read more about this in tutorial [Making ASP.NET application always running](http://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html)?
2. When your application woke up `RecurringJobScheduler` discovered that existing recurring job hadn't been triggered for a long time. So `#70` job was triggered immediately. Then `#71` job was triggered on a schedule. It explains why there's only one hour difference between `#70` and `#71` jobs.

**Comment by rbaezam** [comment]
Hi @aidmsu I'm having a similar issue as the OP. But I'm using dotnet core for my asp.net application. Is there any way to make the application always running with IIS and dotnet core?

Thanks.

**Comment by odinserj** [comment]
@dvladimirovich, @rbaezam, please see #899 to know the solution for ASP.NET Core. Will close this as a duplicate.

**Comment by ramlakhan78** [comment]
Hi everyone :)

I am glad to meet all of you . Actually i am facing a issue with hangfire , i have created a recuring job but it is not firing and it's last  and next execution time is N/A as you can see in this snapshot :)

![image](https://github.com/HangfireIO/Hangfire/assets/172014218/8c3b15d4-94de-46a5-b163-7a10a86b06fb)

My project's hangfire configuration is 

services.AddHangfire(x => x.UseSqlServerStorage(Configuration.GetConnectionString("MSSQL")));

 app.UseHangfireDashboard("/hangfire", new DashboardOptions
 { 
     Authorization = new List<IDashboardAuthorizationFilter> { new MyAuthorizationFilter() } 
 });
 app.UseHangfireServer();
 
 and this is my job code
 
 RecurringJob.AddOrUpdate("change-fighters-fighter-class", () => auto.UpdateFightClassForUser(), Cron.Hourly);
RecurringJob.AddOrUpdate(() => auto.SendInvoiceToUser(), Cron.Hourly);

due to issue i am getting frustration and tearing my hair 
please support and give me a meaningful solution 

Thanks in advance

**Comment by Reepu78** [comment]
hi friends

my case is different to everyone . i want to trigger within 1 min in my application . have published my application on IIS server. it is not working there. it is working fine on my local system. what is wrong with me.
