### ISSUE TITLE
Parameter Mapping issue Int32 to Int64

### ISSUE THREAD

**Issue by sachin5284** [HangfireIO/Hangfire#897]
While adding a Background job I am inserting a method with some dictionary parameter containing Key Value Pair like {ScenarioID,27 }
`BackgroundJob.Enqueue(() => XYZMethod(parameterDictionary));`
where 27 is Int32 but while job is running Hangfire is converting Int32 to Int64. I want to know if issue is with SQL Server or Hangfire apis

**Comment by aidmsu** [comment]
Hi, @sachin5284!

Could you tell me more about `XYZMethod`? What is its signature?

**Comment by sachin5284** [comment]
`IEnumerable<T> SelectAll(IDictionary<string,object> parameters)
{
//code here
}`
Its a method defined in one of the interface i.e. IBusinessRepository<T> for which I used Ninject to Bind with concrete implementation.
I think the datatype is converting when server fetch it from Persistent storage(SQL server).

**Comment by aidmsu** [comment]
@sachin5284 thanks for details!

Your question partly relates to #516.

Hangfire uses **Newtonsof.Json** to serialize and deserialize arguments. Argument `new Dictionary<string,object>{{"ScenarioId", 27}}` serializes into 
```
{"ScenarioId":27}
```
So there is no way to define certain type of `27` value. Even using the `TypeNameHandling.All` serialization settings doesn't help for your case because `Int32` and `Int64` are primitives and **Newtonsof.Json** serializes them without type info.
I strongly recommend not to use complex argument types for backround jobs. It leads to increasing of storage data size, time of background jobs handling and so on. Read more about it in [Best practices](http://docs.hangfire.io/en/latest/best-practices.html#make-job-arguments-small-and-simple) article.

If you still want to use `IDictionary<string,object>` as argument type you can implement custom class `PrimitiveJsonConverter` (read more about custom converters in [Json.NET docs](http://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm)) and use it for serialization in Hangfire:
```
JobHelper.SetSerializerSettings(new JsonSerializerSettings
{
    Converters = new JsonConverter[] { new PrimitiveJsonConverter() }
});
```
**BUT** pay attention that in this case `PrimitiveJsonConverter` will be used for arguments serialization of **all** backround jobs.
