### ISSUE TITLE
Hangfire cannot work when servers running on different code bases use the same database

### ISSUE THREAD

**Issue by vgritsev** [HangfireIO/Hangfire#910]
This issue is somewhat related to issue #908, but provides more details and possible fix.
__Short description__
In a case when multiple instances of Hangfire use the same database, but code is different, Hangfire servers may fail to instantiate jobs. In this case job is rescheduled. 
For instance if I have servers *A.v1* and *A.v2* and I have *JobV1* on *A.v1* and *JobV2* on *A.v2*, server *A.v1* eventually may try to en-queue *JobV2* and fail on de-serialization as codebase is different. 
Queues cannot help to solve this problem as queue information is attached to the job and it is the job that cannot be instantiated. If I have ten *different* servers the job have 10% chance to be re-queued sucesfully.

__Why it matters__
We have quite a few distinct micro-servers which use Hangfire. Let's say we have ten types of servers and they deployed into eight geographic zones in two environments (test and prod). Today we have 16 separate Hangfire databases - one per zone per environment (32 during roll-out). Today we forced to do synchronous deployment to all servers in one zone and environment whenever code for *any* of the job changes.  We also forced to keep all the jobs in a separate common project.  This is a real headache.  
If we want to separate codebase per server type and stop maintaining common job project we looking into maintaining 160 instances of Hangfire databases (actually 320 during the roll-out unless it is synchronous) 

__Possible solution__
When Hangfire selects job for execution in DelayedJobScheduler it specifies *key* parameter to __GetFirstByLowestScoreFromSet__, which is always *"schedule"*.  
In fact Hangfire uses that "schedule" key exactly in four spots: when background job is selected, removed or added to the set.
We propose to change the notion of the key, so it defines not only the job status ("schedule","recurring-jobs",etc) but also a __codebase__, for instance  "schedule_orderManagement_v1.10"
When application starts it specifies (optional) *codebase*, like:
 __GlobalConfiguration.Configuration.UseCodeBase("_orderManagement_v1.10")__
All places in the code which access the set should use *codebase* suffix, which is empty by default and existing functionality is completely unchanged (including queues etc). 

Now I can deploy new version of the code to *any* instance of micro-server in my zone and be sure that other Hangfire instances will not to try to work with the job they cannot instantiate

We have the fix for  "schedule" case right now and actively testing it.

**Comment by plaisted** [comment]
We have apps deployed with a similar model for parallel deployments. For one app we have a bunch of "mission critical" tasks running under hangfire that are stored in a database and a service syncs the tasks listed in the database with the hangfire recurring job scheduler. The tasks in the database specify the version (queue) they target. This allows us to deploy multiple worker versions and cut the tasks over individually in order to reduce our risk if something goes wrong with a deployment.

I haven't noticed any errors (am going to looks through the logs) but maybe we have just gotten lucky that the entrypoint method / assembly has remained constant across our deployments and the assemblies that changed weren't loading during the initial job instantiation/en-queuing. We're also using the netcore Additionally we only have 2-3 versions deployed at a time so even if there are errors chances are it will get picked up by the correct worker reasonable quickly (33%-50% chance right version grabs job). I always assumed the there wouldn't be any issues with assembly mismatches as I didn't expect workers to touch jobs that weren't on their queue (I see I'm wrong).

This seems like a critical issue with the Hangfire backend as 3 out of the 4 production setups I've worked on that used Hangfire use some sort of setup where different queues may have different assembly version (or not have an assembly at all). It appears we're not the only ones using it in this way.

**Comment by dannief** [comment]
@vgritsev We are having the same problem. Could you share your fix?

**Comment by vgritsev** [comment]
After some testing we found that SqlServerStorageOptions.SchemaName is a sufficient solution for our problem. Unfortunately this option is not well documented. Here is what we do now:
            var sqlServerStorageOptions = new Hangfire.SqlServer.SqlServerStorageOptions { SchemaName = Codebase }; //Codebase uniquely identifies the version of the code
GlobalConfiguration.Configuration
                .UseSqlServerStorage(HangfireConnectionString, sqlServerStorageOptions);
Hangfire creates a separate set of table for each schema name in the same database. This way we have a single database and multiple table sets for each code base we have. The only drawback is the fact that we do not have a combined dashboard and we need separate ports  for every dashboard.

**Comment by dannief** [comment]
I think this is still an issue if we require separate dashboards. Not much different than having to have separate databases. For our purposes we need to have one dashboard, so our workaround is to ensure all server instances have references to all job classes

**Comment by Deantwo** [comment]
Duplicate of #595
