### ISSUE TITLE
IElectStateFilter.OnStateElection() broken at 1.6.13

### ISSUE THREAD

**Issue by seancolonello** [HangfireIO/Hangfire#963]
Using Hangfire.Core 1.6.12 and Hangfire.SqlServer 1.6.12 the following IElectStateFilter implementation works fine; its purpose being to immediately fail a job (no retries) when a specific exception is the cause.
```c#
public void OnStateElection(ElectStateContext context)
{
  // Was this re-scheduled earlier in the filter chain (by the default AutomaticRetryAttribute)?
  if (context.CandidateState is ScheduledState)
  { // Is this a retry?
    if (context.TraversedStates.FirstOrDefault(s => s is FailedState) is FailedState failedState)
    { // Is this an explicit fast-fail?
      if (failedState.Exception is FastFailException)
      {
        context.CandidateState = failedState;
      }
    }
  }
}
```
In both 1.6.13 and 1.6.14 this no longer works. The reason being context.CandidateState is never ScheduledState, and TraversedStates is always empty.

**Comment by odinserj** [comment]
Sorry for that change, I was fixing a bug where it was unable to intercept Failed state before the AutomaticRetry filter, and will try hard to not to release such changes in future. The problem is the changed order, you should raise it to be more than [`20`](https://github.com/HangfireIO/Hangfire/blob/501ac6b0c14b2dc4473fec0e82c8e6e747d9def3/src/Hangfire.Core/AutomaticRetryAttribute.cs#L101):

```csharp
public FailFastAttribute : JobFilterAttribute
{
    public FailFastAttribute()
    {
        Order = 30
    }
}
```

**Comment by seancolonello** [comment]
Thanks Sergey, that fixed it.
