### ISSUE TITLE
Scheduled job with 30 15 * * *, failed to run on weekend

### ISSUE THREAD

**Issue by attrib75** [HangfireIO/Hangfire#977]
Should recurring job with that schedule run on Sat and Sun?  Also, it never seems to run at the time when it is scheduled even when its a weekday.

thanks

**Comment by pieceofsummer** [comment]
Yes, it should run every day, since the day-of-week component is `*`. You can easily check your schedule with [crontab.guru](https://crontab.guru/#30_15_*_*_*).

1) Note that scheduled jobs use UTC time zone by default (unless specified otherwise), which may be different from your local time zone.
2) Check if Hangfire server keeps running on the weekends and not being stopped because of IIS worker recycling or anything.

**Comment by attrib75** [comment]
Thank you for responding.   No later than I wrote this that I read the documentation about recurring jobs again.   I think the app pool was stopped,  we're hosting in IIS.  I implemented the sample code that starts the app when the worker prices starts,  and set the app pool to always running.  I'll keep an eye on it. Thanks again!
