### ISSUE TITLE
Creating custom nuget package for DotNet Core

### ISSUE THREAD

**Issue by smetronic** [HangfireIO/Hangfire#996]
Hi, i have made some few changes in the hangfire source so the hangfire  dashboard theme matches with my DotNet Core app, i am able to compile the source and make it work with .net framework application but i have no idea how to make this work with DotNet Core app. My only guess is to export this as a DotNet core nuget package. -Thanks

**Comment by pieceofsummer** [comment]
You can add your modified project to your solution (as is, or as a git submodule), and reference it from your project(s).

You can also build it as a NuGet package and configure a [local NuGet repository](http://www.marcusoft.net/2011/09/creating-local-nuget-repository-with.html).

**Comment by smetronic** [comment]
I tried to add a reference of modified HangFire in my DotNet Core app but it didn't work, it returned an exception that the framework didn't matched. I also tried to build a nuget package for Dotnet Core but failed. The build.bat is returning a lot of errors.

**Comment by pieceofsummer** [comment]
@smetronic the built.bat doesn't work for me either, but compiling in Visual Studio works somehow.

You may also create new .NET Core `csproj`s instead of the existing ones. Just be careful with resource files, as they're expected under namespace different from the one inferred from project name (i.e. "Hangfire.Dashboard.Content…" instead of "Hangfire.Core.Dashboard.Content…")

**Comment by smetronic** [comment]
I'm getting a lot of references errors, can't i get the built.bat to work.

**Comment by smetronic** [comment]
I fixed the references the application is working. thanks
